### ISSUE TITLE
[ProjectTracking]: Ethereum address implicit accounts

### ISSUE THREAD

**Issue by staffik** [near/nearcore#10018]
See [Near One project tracking issue](https://github.com/near/near-one-project-tracking/issues/7) for context.

# Task list
- [x] Introduce distinction for 40 characters long hexadecimal addresses prefixed with `0x`, but treat them identically as named accounts for now.
   - https://github.com/near/near-account-id-rs/pull/14
   - https://github.com/near/nearcore/pull/10020
- [x] [[Old design](https://github.com/near/NEPs/issues/498#issuecomment-1771684663)] Add protocol feature (`EthImplicit`) supporting: https://github.com/near/nearcore/pull/10056
   - Creating account without access key on transfer to ETH-implicit address.
   - Adding access key (if does not exist) to this account when sending transaction from this account and public key matches.
- [x] [[New design]](https://github.com/near/NEPs/issues/518#issue-1996465013) Create a new implementation according to the new design: https://github.com/near/nearcore/pull/10224
   - When creating a new ETH-implicit account, deploy the `Wallet Contract` (from now a part of the protocol) to that address. For now use a placeholder, empty contract.
   - Make sure no access key is added to ETH-implicit account. No transactions should be possible from the address.
- [x] Add Wallet Contract placeholder implementation that only allows to transfer funds. Do not literally deploy the contract. https://github.com/near/nearcore/pull/10269
- [ ] Merge the `wallet_contract` into the workspace. Address the issue of reproducible builds (WASM file hash).
- [ ] Handle mapping ETH-implicit accounts and keys for the `mirror` tool.
- [ ] Add Python-based tests for ETH-implicit addresses.
- [ ] Stabilize, change protocol version, update documentation.

**Comment by wacban** [comment]
Nice tracking issue! 
Another item that would be good to track here is to handle the existing accounts with the eth implicit account format.

**Comment by wacban** [comment]
cc @walnut-the-cat fyi here is the tracking issue for this project

**Comment by staffik** [comment]
@marcelo-gonzalez are there plans to remove the mirror / fork-network tools?

**Comment by marcelo-gonzalez** [comment]
> @marcelo-gonzalez are there plans to remove the mirror / fork-network tools?

nope don't think so, as right now we're using them for release testing and just testing with a multi-node setup in general

**Comment by staffik** [comment]
Completed for now, see https://github.com/near/near-one-project-tracking/issues/7#issuecomment-1934486187
