### ISSUE TITLE
Tracking issue: chunk validator assignment integration

### ISSUE THREAD

**Issue by mooori** [near/nearcore#10014]
Tracking issue for the integration of chunk validator assignment (#9983) with the rest of the system:

- [ ] Determine an initial value for `min_mandates_per_shard`.
  - [This messages](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/validator.20seat.20assignment/near/393792901) provides a potential value and the enclosing Zulip topics contains/links more info regarding the analysis of security properties of chunk validator assignment.
  - This is relevant for [constructing ￼`ValidatorMandatesConfig`￼](https://github.com/mooori/nearcore/blob/20d225f652b772971b80b2c01c5df25d5ded5f7e/core/primitives/src/validator_mandates.rs#L31-L35).

- [ ] Determine an initial value for `stake_per_mandate`.
  - Ideally it’s chosen such that the resulting number of mandates is close to `num_shards * min_mandates_per_shard`.
  - This is relevant for [constructing ￼`ValidatorMandatesConfig`￼](https://github.com/mooori/nearcore/blob/20d225f652b772971b80b2c01c5df25d5ded5f7e/core/primitives/src/validator_mandates.rs#L31-L35).

- [ ] Lower `stake_per_mandate` dynamically when there are not enough mandates for all shards with the current set of validators.
  - The number of mandates should not grow unboundedly as validator assignment becomes more expensive as the number of mandates increases.
  - Currently this code is hit only in tests so we simply [panic](https://github.com/mooori/nearcore/blob/20d225f652b772971b80b2c01c5df25d5ded5f7e/core/primitives/src/validator_mandates.rs#L77-L81).

- [x] Introduce a protocol feature which determines whether `EpochInfo::new()` should return `EpochInfo::V3` or `EpochInfo::V4` ([ref](https://github.com/near/nearcore/pull/9983#discussion_r1372185798)).
    - We ended up adding the protocol feature in #9983. See [this conversation](https://github.com/near/nearcore/pull/9983#discussion_r1373695805).

- [x] Shuffle shard ids to avoid a bias towards smaller shard ids ([ref](https://github.com/mooori/sim-validator-assignment/pull/12#discussion_r1389895314)).
    - #10298
