### ISSUE TITLE
[Betanet] Address the issues found during the Node-internal testing of new Betanet

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#10043]
Address the issues found during the Node-internal testing of new Betanet
```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/10117
- [ ] https://github.com/near/nearcore/issues/10116
- [ ] https://github.com/near/nearcore/issues/10121
- [ ] https://github.com/near/nearcore/issues/10122
```
