### ISSUE TITLE
🔷 2023-11 milestone: Continuing threat modeling & generic security work

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#10068]
Previous milestone: #9604

**Carryover from #9604**
- [ ] Get reviewed and publish the changes to our security release process

**Generic security things**
- [x] Setup a code coverage infrastructure
- [x] Read through the provisional Hacken audit report, and get the issues fixed

**Continuing threat modeling**
- [ ] Chat with 5 more people from protocol about security
- [ ] (Aspirational) Chat with 10 more people from protocol about security

**Adding fuzzers**
- [ ] (Aspirational) Add fuzzers for host functions

**Miscellaneous**
- [ ] (Aspirational) Look into our current Hackenproof reports

**Not planned, kept for reference when writing future milestones**
- (Not planned) Search for the next best place to fuzz
- (Not planned) Investigate which projects could be helpful to us from https://github.com/rust-secure-code/projects

**Comment by abdullah502lA** [comment]
aboodg502
