### ISSUE TITLE
🔷 [2023-11] zkASM backend produces machine code the right way

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#10106]
This is the continuation of the previous month’s

* https://github.com/near/nearcore/issues/9623

Just like the last time I would like to ensure that we have

* [ ] Proper register definitions;
* [ ] Proper ABI definitions;
* [ ] That we apply relocations in the right places;
* [ ] Remove the unnecessary remnants of RISC-V so that there is less confusion when trying to make changes to the backend.

In addition to this I would like to extend the scope of my work to

* [ ] Use the preexisting testing infrastructure;
* [ ] Ensure that vcode output makes sense for zkasm backend.

**Comment by nagisa** [comment]
The update here is pretty late – I had broken my leg and was not in a working condition for the entirety of December and some of the latter part of November.

Before then I was only really able to make some progress towards cleaning up the remnants of RISC-V:

* https://github.com/near/wasmtime/pull/77
* https://github.com/near/wasmtime/pull/93
* https://github.com/near/wasmtime/pull/94

And to start looking into our testing infrastructure:

* https://github.com/near/wasmtime/pull/86

My memory of the November is also that I had scaled back my involvement with the zkASM project slightly to make additional time for maintenance of nearcore code

https://github.com/near/nearcore/pulls?q=is%3Apr+author%3Anagisa+is%3Aclosed++created%3A2023-11-01..2024-01-01+

which might explain somewhat unsatisfactory progress given the ambigious goals I had set for myself initially.
