### ISSUE TITLE
[ProjectTracking]: Stateless Validation benchmarking

### ISSUE THREAD

**Issue by staffik** [near/nearcore#10543]
## Context
[Stateless Validation tracking issue](https://github.com/near/near-one-project-tracking/issues/20).

### Goal
Stateless Validation should be benchmarked and analyzed in a presentable format.

### Motivation
* Performance optimization and stability enhancement should be in place based on incoming data.
* [Bowen Wang](mailto:bowen@near.org) plans to share findings from Stateless validation StatelessNet during EthDenver (Feb 29th).
* We need enough confidence on resilience, scalability, reliability of the network before completing StatelessNet (March 31st).

## Tasks
- [x] Prepare and share a plan for benchmarking. [Zulip](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/Stateless.20Validation.20benchmarking/near/420455575)
- [x] Run locust scenario against StatelessNet, possibly finding issues. [Zulip](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/StatelessNet.20loadtests/near/421050115)
- [x] Run locust scenario against adversenet, comparing current Mainnet binary with StatelessNet binary. 
- **(ideally due February 15th)** _In-memory trie is ready._
- [x] Run the locust scenarios again with in-memory trie enabled (against StatelessNet and adversenet).
- [x] **(due February 21st)** Compare data for 3 binary versions: current Mainnet, Stateless Validation with / without in-memory trie and write up a report for EthDenver.
- **(February 29th)** _EthDenver_
- [ ] **(March 15th)** Check-in, discuss if we have enough confidence in the network.
- [ ] **(March 31st)** Wrap up the StatelessNet test and share the final report.

## Prerequisites (ideally due February 15th)
- https://github.com/near/nearcore/issues/10462
- https://github.com/near/nearcore/issues/10563
- https://github.com/near/nearcore/issues/10564

**Comment by staffik** [comment]
Due. Feb 21st
We would like to have some performance data on what stateless validation and In-memory trie can enable. For instance, performance improvement data for fungible token transfer per sec per shard. We acknowledge that the number may not be accurate until all optimization/stabilization/bug-fixes are in, but Bowen can use such data to give high level overview during EthDenver.
