### ISSUE TITLE
[ProjectTracking] Non-refundable storage

### ISSUE THREAD

**Issue by staffik** [near/nearcore#10551]
## Context
[Near One project tracking](https://github.com/near/near-one-project-tracking/issues/8).
NEP: https://github.com/near/NEPs/pull/491.

### Goal
We aim to enable the sponsorship of accounts with arbitrary storage (for example, with a contract that exceeds the zero balance account limit). Currently, there is a financial incentive to deplete such a sponsor by deleting the account and then cashing in.

## Tasks
- [x] When an account has nonrefundable storage balance, should it show up as balance in the Rosetta RPC adapter? https://github.com/near/nearcore/pull/9600#discussion_r1489763971
- [x] Main implementation. https://github.com/near/nearcore/pull/9600
- [x] Switch to `permanent_storage_bytes` instead of `nonrefundable` account field. https://github.com/near/nearcore/pull/10701
- [ ] #10977
- [ ] Stabilization.

## Follow-up tasks
- [ ] Refactor constructing new accounts.
- [ ] Refactor wallet contract tests.

**Comment by staffik** [comment]
2024-02-05 status update:
* We have implementation reviewed by 3 reviewers and ready to merge.
* But we are [waiting](https://github.com/near/nearcore/pull/9600#discussion_r1474776186) on a resolution of a question to Coinbase.
  * "Should we show non-refundable balance as balance in Rosetta RPC adapter?"

**Comment by staffik** [comment]
For now, NearOne will assume that the project is on pause and won't work on it, until Emerging technologies team reach to us.
cc @walnut-the-cat
