### ISSUE TITLE
[Tracking issue] contract runtime work on alleviating congestion on mainnet

### ISSUE THREAD

**Issue by akhi3030** [near/nearcore#10981]
A tracking issue for what the team is currently working on and plans to work on in the near future.
```[tasklist]
### Critical Tasks
- [ ] https://github.com/near/nearcore/issues/10885
- [ ] https://github.com/near/nearcore/issues/11107
- [ ] https://github.com/near/nearcore/issues/11033
- [ ] https://github.com/near/nearcore/issues/10971
- [ ] https://github.com/near/nearcore/issues/10970
- [ ] https://github.com/near/nearcore/issues/10972
- [ ] https://github.com/near/nearcore/issues/10851
- [ ] https://github.com/near/nearcore/issues/10987
- [ ] https://github.com/near/nearcore/issues/11002
- [ ] https://github.com/near/nearcore/issues/11035
- [ ] https://github.com/near/nearcore/pull/11022
```
```[tasklist]
### Nice to have
- [ ] https://github.com/near/nearcore/issues/10979
```
