### ISSUE TITLE
Blockers and Wishlist for the 1.39.1 release

### ISSUE THREAD

**Issue by VanBarbascu** [near/nearcore#11015]
This a dependancy tracker issue for the next release. Please add **_only fixes and optimisations_** you want to be included in the release.

```[tasklist]
### List of **proposed** fixes
- [x] prefetch: claim.sweat::claim (#11094)
- [x] routing: remove offloading of unreachable components to DB (#11018)
- [x] Preallocate the LruCache inside the `TrieCache` and use a Mutex for trie caches (#10995)
```
