### ISSUE TITLE
[Tracking issue] Setup a continuous benchmark for single-shard throughput

### ISSUE THREAD

**Issue by akashin** [near/nearcore#11348]
This is a tracking issue for setting up the benchmark that runs every day on the latest version of nearcore with a purpose of measuring the throughput that we can achieve on a representative workload.
It is a first step towards https://github.com/near/nearcore/issues/10885

At the moment we are focusing on the following setup:
- NEAR network with a single-shard
- Traffic generated with [Locust](https://github.com/near/nearcore/blob/master/pytest/tests/loadtest/locust/README.md) Fungible Token (FT) benchmark
- The size of the FT contract needs to be big enough to expose costs of storage operations similar to the ones on mainnet
- Network settings close to mainnet (e.g. epoch length of ~24 hours)

The current findings are described in [this document](https://docs.google.com/document/d/1NRYRkJUjVAb5djJKNY6Vl4gyXyNCOE48P_KscD3Sy1Y/edit#heading=h.vaggmohjfzwf).

```[tasklist]
- [ ] https://github.com/near/nearcore/issues/11351
- [ ] https://github.com/near/nearcore/issues/11359
- [ ] https://github.com/near/nearcore/issues/11404
- [ ] https://github.com/near/nearcore/issues/11405
- [ ] https://github.com/near/nearcore/issues/11352
- [ ] https://github.com/near/nearcore/issues/11458
- [ ] https://github.com/near/nearcore/issues/11459
- [ ] https://github.com/near/nearcore/issues/11460
- [ ] https://github.com/near/nearcore/issues/11630
```

**Comment by akashin** [comment]
A related issue about the same benchmark with multiple shards: https://github.com/near/nearcore/issues/11347

**Comment by MCJOHN974** [comment]
Status update:

Currently don't work, hope #11395 will fix that. Setup I'm trying to start is pretty simple -- 1 node, 1 shard, locust and neard on same machine, FT contract state flashing on each commit.

**Comment by MCJOHN974** [comment]
Upd: now we have continuous benchmark, description: https://github.com/near/nearcore/issues/11404.

**Comment by akashin** [comment]
A summary of the current progress:
- We have ran the benchmark with multiple configurations:
   - With 1, 2 and 6 shards - the throughput scales roughly linearly for this workload
   - With 10 PGas gas limit - the throughput scales roughly linearly for this workload
   - [With in-memory trie enabled](https://github.com/near/nearcore/issues/11458) - didn't see any noticeable improvement at the current state size, need further investigation
   - On different hardware - the throughput heavily depends on it and has disk and CPU as bottlenecks
- We have a [database](https://github.com/near/nearcore/tree/master/benchmarks/continous/db) to store benchmark results and [Grafana dashboard](https://nearone.grafana.net/d/fdo204e4y88owa/continouos-benchmarks?orgId=1) visualizing it
- [Experimented](https://github.com/near/nearcore/issues/11359) with a creation of a larger state for FT contract, this needed further optimizations to be performant enough
- Set up [automated runs](https://github.com/near/nearcore/issues/11404) of the benchmark every day

Next steps:
- Publish benchmark results to DB and Grafana automatically
- Make benchmark more representative
   - Larger contract state size
   - Larger network (>5 validators)
- Investigate disk bottleneck at high throughput
- Automate search of optimal gas limit
- Quantify effects of in-memory trie

**Comment by akashin** [comment]
A summary of the current progress:
- @akashin , @Ekleog  Prepared a larger contract state for the benchmark (5 GB of contract size, 250GB of on-disk state): https://github.com/near/nearcore/issues/11359
- @MCJOHN974 together with @mooori managed to send the first data point to benchmark DB from GCP using the end-to-end script https://github.com/near/nearcore/pull/11604
- @akashin [measured effects](https://github.com/near/nearcore/issues/11458#issuecomment-2165999536) of in-memory in a setup with no trie caches and minimal state - it yields ~30% throughput improvement
- @akashin submitted Terraform scripts for setting up machines for a multi-node run: https://github.com/Near-One/infra-ops/pull/133

Next steps:
- Find interesting workloads to test with a large contract size - this is not trivial, as the workload needs to keep the working set large, as otherwise all state will be cached and we will see no difference with a setup with no state (@akashin)
- Set up a cron job to run the end-to-end script on GCP every day (@MCJOHN974)
- Run experiment with larger gas limit of 3 PGas (@MCJOHN974)
- Prototype automatic gas limit adjustment for https://github.com/near/nearcore/issues/11460 (@mooori)
- Run the benchmark with multiple validator nodes (@akashin)

**Comment by akashin** [comment]
To summarize latest progress:
- We now have a benchmark that runs every 2 hours and is visualized [on Grafana](https://grafana.nearone.org/d/fdo204e4y88owa/continuous-benchmarks?orgId=1) (by @MCJOHN974)
- The large contract state is ready and can be used in the benchmark (@akashin)
  - Example run can be found in https://grafana.nearone.org/goto/TYz8A3wIR?orgId=1, https://grafana.nearone.org/goto/TYz8A3wIR?orgId=1
  - It behaves as expected and slows down the network operation
  - We still need to tune the size of the state that we actually want to use and enable it in the periodic benchmark runs
- The work on automatic gas limit is in progress and we have a prototype that searches for optimal limit (@mooori)

I think we can close this off and continue the future work in https://github.com/near/nearcore/issues/11680:
- Running a benchmark with multiple nodes
- Using optimal gas limit
- Using appropriate state size
