### ISSUE TITLE
[Tracking issue]: db for continuous benchmarks

### ISSUE THREAD

**Issue by mooori** [near/nearcore#11426]
This issue tracks tasks related to setup of and interaction with the db that stores stats/results of continuous benchmarks.

## DB info

- PostgreSQL 15 hosted on Cloud SQL: [crt-benchmarks](https://console.cloud.google.com/sql/instances/crt-benchmarks/overview?project=nearone-crt)
- Integrated as data source `crt_benchmarks` in N1 Grafana.

## Tasks
- [x] Create PostgreSQL db in Cloud SQL.
- [x] Configure the db to enable integration as a Grafana data source. [[ref](https://near.zulipchat.com/#narrow/stream/295302-general/topic/SQL.20DB.20as.20Grafana.20data.20source)]
- [x] Add it to N1 Grafana as data sources.
- [x] Create a schema for the table storing ft transfer related data. #11418
- [x] Add role with permission suited for machines running benchmarks, giving them write access.
- [x] Add db credentials to N1's 1password to share it safely.
- [x] Document db setup and push a `Justfile` with commands to make it reproducible.
- [x] Document db admin tasks and push a `Justfile` with commands.
- [x] Create a Grafana dashboard to display `ft transfer` data.
- [x] [To be confirmed] write a very simple CLI to make db interaction easier, based on an ORM (e.g. [Diesel](https://diesel.rs)).
  - Motivation: Avoid hand writing SQL which is tedious and error prone.

**Comment by mooori** [comment]
Closing as completed as the db is set up and a CLI tool implemented, see [here](https://github.com/near/nearcore/tree/af022d8b30b8372abf5671fb32dffcd7e7000618/benchmarks/continous/db).
