### ISSUE TITLE
🔷 [Project Tracking] Resharding v3

### ISSUE THREAD

**Issue by wacban** [near/nearcore#11881]
# Goals 

* The ability to increase the blockchain capacity by increasing the number of shards
* The ability to balance the load across shards 
* The ability to do the above fast
* The ability to do the above automatically (dynamic resharding)

# References

[Resharding Docs](https://docs.google.com/document/d/1znvFZyQKIgPcrmzfevOmzTKN8p0T5w8dfK-VyW1W-4g/edit#heading=h.3sszd3zfpu1i)
[Resharding V2 tracking issue](https://github.com/near/nearcore/issues/8992 )

# Tasks

- [ ] MVP Implementation
  - [x] #12019 @Longarithm 
  - [x] MemTrie @shreyan-gupta 
  - [x] #12174 FlatState @Trisfald 
  - [x] #12050 @staffik 
  - [x] State Sync @marcelo-gonzalez 
  - [x] Shard Layout and non-contiguous shard ids @wacban 
  - [ ] boundary accounts
  - [ ] Multiple resharding support
  - [ ] Misc
    - [ ]  #12552 
    - [ ] Transaction Pool resharding
    - [x] Congestion Control integration
    - [x] Yield Resume integration
    - [ ] Cold Storage integration (inc not losing data again)
    - [x] ReadRPC integration
    - [x] Make sure that all nodes have memtrie enabled
    - [ ] Node Restart handling
    - [ ] Fork handling & double signing
    - [ ] Validator Assignment
    - [ ] Chunk Headers have old data (inc shard id) when chunk is missing
    
- [x] Design
  - [x] [Resharding Ideas Comparison](https://docs.google.com/document/d/1AizkvBibsyWTAAeHPCeqjyc_c6yiHJZ8DROzHEqyg1Y/edit)
    - Decision: **Instant Resharding**
  - [x] Shard splitting
    - [x] Instant Resharding
    - [x] Continuous Balancing
    - [x] Resharding v2.1
  - [ ] Automatic Scheduling
  - [ ] Mid-Epoch / Next-Epoch Resharding

## Design - Instant Resharding

- [x] High level design
  - [doc](https://docs.google.com/document/d/1F19DloPgjeTxo0EUVY5LRq9L9v_iN6VwVex9i1RYo-M) 
- [x] #11907 @staffik 
  - [ ] How to split state in the db (inc migration if needed)
  - [ ] How to clean state after state sync
  - [ ] How to clean state after resharding (parent state)
  - [x] overview [doc](https://docs.google.com/document/d/1QSs74ZhsuhDkY68BA06t3JZXC7CnGp0zdRZgMVEyl6Q/edit#heading=h.nj72adwv5w86)
  - [ ] `node hash` @wacban 
    - [x] design [doc](https://docs.google.com/document/d/1qJMouoJSl_L7mbQC5LOIAdJajNj_1W_BHciJWPArfQE/edit)
    - [ ] migration feasibility
  - [x] Shard Columns @staffik 
    - [x] [doc](https://docs.google.com/document/d/1W1vjuYgLk5oaspnld5wK8i7v8PLj4tdIiSzRlPULzwA/edit) 
  - [x] Mapping @shreyan-gupta 
  - [ ] Getting rid of State @tayfunelmas 
- [ ] #11909 @Longarithm 
- [ ] Storage - MemTrie @shreyan-gupta 
  - [x] How to split state in memory
  - [ ] How to clean state after state sync
  - [ ] How to clean state after resharding (parent state)
  - [x] Estimate the overhead and hardware requirements
  - [ ] Estimate how much time does it take to clone memtrie arena
- [ ] State Sync integration @marcelo-gonzalez 
  - [ ] State for epoch T + 2 is dumped in T
  - [ ] `StateSyncDumpProgress::Skipped`
  - [ ] receipts proofs (`filter_incoming_receipts_for_shard`)
- [ ] Shard Merging  
- [x] #11966

## Design - Continuous Balancing @Longarithm & @Trisfald 
- [x] High level design
  - [doc](https://docs.google.com/document/d/1IPiF37quJImgz82CijvIwup1C25x1SATSQKtZtWVl-A)
- [x] Design document WIP
  - [doc](https://docs.google.com/document/d/1zFjbEb6wflGSW6HiIXUKEdRidsuSLH_B5qQppqDSuwE/edit?usp=sharing) 
  - [x] How to handle large accounts? 
    - [x] account transfer
    - [ ] balancing manager should prevent large / busy accounts from hopping back and forth
  - [x] Estimate and address the balancing overhead.
  - [x] Account availability during transfer. 
  - [x] How to handle all sorts of receipts? 
  - [x] Estimate impact on the archival node storage. 
  - [x] Consider implementing a limit on account size.
  - [ ] Polish and verify design assumptions

## Design - Resharding v2.1 @wacban 

The old resharding is not particularly interesting because it takes at least an epoch to take effect. It's here mostly for completeness but it may be also worth considering it as a milestone towards the v3. Viability depends on the overlap with the end goal design and the amount of throw away work. 

- [x] High level design, Short Epochs
  - [Resharding 2.1](https://docs.google.com/document/d/1HBc33-Sxse88tGqlLx6v3b0ESs27U18dsQEPgfE8d60/edit)
- [ ] Suitability as milestone towards Instant Resharding

##  Design - Automatic Scheduling aka Dynamic Resharding

- [x] High level design
  - [Resharding Manager](https://docs.google.com/document/d/1I2ZJUeUlnMwcgI4piKez1T3nMbRhmUGAGTHnEw89y_c/edit)
- [ ] ReadRPC integration

## Design - Mid-Epoch / Next-Epoch Resharding

The typical resharding operations, splitting and merging shards, require changes to the validator assignment. In order to execute resharding fast we will need to enhance the assignment to be able to be adjusted without the usual two epoch delay. 

- [x] High level design
  * [doc](https://docs.google.com/document/d/1lQ2Ec7chVSuOVUc7LjbeaGbjayQ-dyOvhsSrrtDq42A/edit)
  * Some ideas were presented in the Instant Resharding doc
  * Mid-Epoch may not work well with State Sync :(

**Comment by wacban** [comment]
The design phase is now completed. We will be implementing the Instant Resharding approach. I will rearrange the issue to reflect the current work and I'll move the design task list down the description.

**Comment by walnut-the-cat** [comment]
Sept 2-13
* flat storage and state witness designs review and discussion
* resharding proof generation discussion
* memtrie implementation discussion
* proposal for changes to the state sync epoch during catchup and its implementation
* state handling: #12050 
* mapping strategy for state implmenetation: #12084 
*
