### ISSUE TITLE
[Project tracking] Cross shard bandwidth limits

### ISSUE THREAD

**Issue by jancionear** [near/nearcore#11920]
* Central doc: https://docs.google.com/document/d/1ypp-RahbfibGypPcfh7LdnLq2xSKGXd505-aovDPYcQ/edit#heading=h.6n0d8rflejy8

TODO list:
* [x] - Produce (mock) bandwidth requests during chunk application
* [x] - Put produced bandwidth requests in chunk headers
* [x] - Pass bandwidth requests from previous chunk headers to chunk application
* [x] - Maintain bandwidth scheduler state
* [x] - Generate bandwidth requests based on receipts stored in the outgoing buffers
* [x] - Implement the core bandwidth scheduler algorithm - process requests and grant bandwidth based on the requests
* [x] - Distribute remaining bandwidth after the core algorithm that fulfills requests in finished
* [x] - Add bandwidth scheduler parameters to runtime config
* [x] - Metrics
* [x] - Testing, testing, testing
* [x] - Benchmark to calculate throughput improvements
* [x] - Revisit TODOs before stabilization
* [x] - Write the NEP
* [x] - Get the NEP approved

**Comment by walnut-the-cat** [comment]
Aug 30th report:
* lots of thinking and discussions. Making progress, it seems that we have a few potential designs to choose from, now we have to iron out all the details and choose which one to go with.
  * [Design doc link](https://docs.google.com/document/d/1ypp-RahbfibGypPcfh7LdnLq2xSKGXd505-aovDPYcQ/edit?usp=sharing)

**Comment by walnut-the-cat** [comment]
### Sept 2-6
* Created a central [doc](https://docs.google.com/document/d/1ypp-RahbfibGypPcfh7LdnLq2xSKGXd505-aovDPYcQ/edit)
* Considered a few different solutions to the problem, created quick docs for each one
* Decided to go with option C2

### Sept 9-13
* Not too much progress due to focus on release engineering

**Comment by jancionear** [comment]
### Sept 16-20
* Writing a NEP which describes the chosen design, [WIP version](https://github.com/jancionear/NEPs/blob/crossband/neps/nep-crossband.md)
* Finalizing the design, started writing a simulator to test and validate the algorithm

### Sept 23-27
* Implemented a bandwidth scheduler simulator. it simulates a blockchain that sends receipts between shards in different ways with missing chunks and blocks. Implemented a few different scenarios to test that the BandwidthScheduler maintains high bandwidth utilization and fairness. The initial design had some flaws, but I improved the algorithm and now it's able to achieve the desired behavior. [zulip](https://near.zulipchat.com/#narrow/stream/295558-core/topic/Cross-shard.20bandwidth.20limiting.20presentation/near/473799898)
* The algorithm has been verified on the simulator, it's now ready for implementation  in nearcore

**Comment by jancionear** [comment]
### Sept 30- Oct 4
* Sick

### Oct 7 - 11
* Still sick for a few days
* Ported the implementation from simulator to nearcore, made a quick and dirty prototype to get the idea of how the implementation will look like. Resolved some problems that weren't present in the simulator.

### Oct 14 - 18
* Began implementation of bandwidth scheduler in nearcore. Implemented propagation of bandwidth requests and other wiring needed for the actual bandwidth scheduler algorithm: https://github.com/near/nearcore/pull/12234

**Comment by walnut-the-cat** [comment]
are we done? can we close the issue?
