### ISSUE TITLE
[Tracking Issue] Flat storage for resharding V3

### ISSUE THREAD

**Issue by Trisfald** [near/nearcore#12174]
Part of #11881

## Goal
Support resharding V3 for Flat Storage. On shard layout, Flat Storage must be able to take a shard and split it into two children.
The entire process will happen in the background with no strict time requirement. Additional processing resources consumption should be minimal because, in the meantime, the node will continue to apply blocks and chunks.

## Sub-tasks
- Implementation
  - [x] Support for splitting a Flat storage shard
    - [x] Handle all Flat storage key-value pairs
      - [x] Simple keys
      - [x] Receipts-like keys
    - [x] Possibility to interrupt resharding
    - [x] Background processing
    - [x] Creating children shards and applying deltas
    - [x] Handle parent shard deletion
  - [x] Add observability
    - [x] Log progress of background task
    - [x] Log progress of catchup
    - [x] Time shard deletions operations
    - [x] Metric for status of flat storage (?)
    - [x] Metric for progress for split / catchup
  - [x] Integration with ReshardingManager
  - [x] Handle parent flat storage deltas split
  - [x] Better limits on background task iteration, like key size
  - [x] Trigger memtrie rebuild
  - [x] Configuration option to control shard catchup batch size
  - [x] Delay shard split until resharding block is final
  - [x] Chain forks handling
    - [x] Forks
    - ~[ ] Double signing corner cases~ 
    _We decided to not implement any safeguard. The scenario is very rare and impacted node can be recovered from an healthy snapshot._
  - [x] Tune resharding config for mainnet load
- #### Tests
  - [x] Unit tests
    - [x] Basic flat storage resharder functionality
    - [x] Splitting simple keys
    - [x] More complex resharding with other types of keys
    - [x] Catchup children
    - [x] Parent flat state deltas handling
    - [x] Test for multiple resharding events
    - [x] Test forks and double signing
  - Integration tests
    - To be covered with test loop resharding test
  - Test with forknet: resharding, restart
    - To be done for resharding as a whole 
- #### Nice to have
  - [ ] Refactoring to avoid sending an instance of FlatStorageResharder inside actor messages. 
  - [ ] Refactoring: merging FlatStorageResharder and ReshardingActor

**Comment by Trisfald** [comment]
merged #12164 tackling the introduction of `FlatStorageResharder` and simple key splitting

**Comment by Trisfald** [comment]
merged #12223 to handle all key types
