### ISSUE TITLE
Cleanup trie state parts logic

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#1603]
Improve the format for creating and applying state parts, make it cleaner and more understandable for the reader.

## Other notes

*   [ ] `visit_nodes_interval` gets the keys for beginning and end, and then uses TrieIterator and keys comparison at each step - everything else is linear in the size of the data, but this part could be bad for really long keys with a common prefix. Need to improve or make sure we have a max limit on key length.
*   [x] `validate_trie_nodes_for_part` validates that all nodes are there and also that no extra nodes are included - the error in both cases is `StorageError::TrieNodeMissing` which could be misleading.
*   [ ] `visit_nodes_interval` - the set of nodes included in a state part is defined by the current implementation, ideally we should have a simple strict definition

**Comment by Longarithm** [comment]
Devnote: why the heck we have `Trie::traverse_all_nodes` in tests which kind of replicates logic from other method...

**Comment by Longarithm** [comment]
#9122 adds missing storage error kind.
