### ISSUE TITLE
Storage refactoring

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1666]
Upd 2018-11-18: Promoting this issue to a larger scope.

# Motivations
* Cost of the transaction depends on the trie depth, hence to properly charge we need to know how many nodes were looked up / updated during reads and writes;
* We need to know the size of the key/value before we read them from storage so that we can apply a fee first (currently reading a 1MiB value costs 37% of the fee of calling an empty smart contract, which means someone can do a 2x grind by reading a 3MiB value);
* We are not de-duping values, see Issue: https://github.com/nearprotocol/nearcore/issues/1431
* Iterating over the trie is inefficient -- iteration speed depends on the size of the keys and iterating over keys is slower than looking up keys sequentially, probably because iterator verifies an expensive stopping condition on each step of iteration;
* We don't really need a merkelized trie until the block is finalized;
* One can create a very deep evil trie by constructing keys in a special way.

# Design

The new design should have the following properties:
* The keys are stored separately from the values;
* Keys are hashed and the hashes are used to build the merkle tree;
* We only use merkle tree for the proofs, and do not iterate over it during contract execution;
* We need to change the `External` trait API to allow peeking the size of the values before reading them.

# Work items

- [x] - Split keys from values. ETA 11/20
- [x] - Have a prototype of the storage that includes changes to `External` to unblock fee changes. ETA 11/27
- [ ] - Finish the rewrite of the storage ETA Jan - Feb 2020

**Comment by nearmax** [comment]
We are currently revisiting the storage format and might move from this format entirely.

**Comment by nearmax** [comment]
Reducing the scope to https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/nearprotocol/nearcore/2215 and moving to the Ice Box until after the Stakewars launch.

**Comment by bowenwang1996** [comment]
I believe the work items are done. New ideas to improve storage can be found in https://github.com/near/nearcore/discussions/4326 and https://github.com/near/nearcore/discussions/4413
