### ISSUE TITLE
Compile with stable Rust

### ISSUE THREAD

**Issue by frol** [near/nearcore#2260]
Currently, nearcore can only be compiled with nightly Rust compiler due to the following unstable features:

* [ ] wasmer-singlepass-backend requires [`proc_macro_hygiene`](https://github.com/rust-lang/rust/issues/54727)*

  \* *It seems that Rust 1.44 can have the necessary parts of it stabilized! https://github.com/rust-lang/rust/pull/68717*
* [x] dynasm [dependency of wasmer-singlepass-backend] [requires](https://github.com/CensoredUsername/dynasm-rs/issues/31#issuecomment-562802021) - 0.7.0 release is going to be compilable on stable Rust 1.45:
  * [x] [`proc_macro_diagnostic`](https://github.com/rust-lang/rust/issues/54140) (can be easily conditionaly disabled on stable)
  * [x] [`proc_macro_span`](https://github.com/rust-lang/rust/issues/54725) (it seems that it can be mocked on stable)

It seems that we can have nearcore compiled on stable Rust once `proc_macro_hygiene` is stabilized (mid June?) and `dynasm` has unstable features under feature flags.

/cc @nearmax @bowenwang1996

**Comment by frol** [comment]
dynasm-rs 0.7 release [should be compilable on stable Rust 1.45 release](https://github.com/CensoredUsername/dynasm-rs/issues/31) (the release is scheduled for July 16th), so it seems that it is only a matter of wasmer singlepass backend to upgrade to dynasm-rs 0.7 release (https://github.com/wasmerio/wasmer/issues/1488).

/cc @nearmax @olonho

**Comment by olonho** [comment]
Great to know!

**Comment by frol** [comment]
dynasm-rs has its 1.0 release (they decided to have this milestone of compilation on stable Rust 1.45+ clearly communicated).

wasmer needs to migrate to this new version and they [claim](https://github.com/wasmerio/wasmer/pull/1489#event-3556183919) that the support is already addressed in their [new refactored version of wasmer](https://github.com/wasmerio/wasmer/issues/1495#issuecomment-655224972):

> We are working on the new version of Wasmer that will be released to the public soon.
>
> In this new version we are already using the latest version of Cranelift (that also supports Aarch64), and have passed all tests successfully in our ARM servers.
>
> So we just have to wait for a few weeks to see the support upstream! :)
