### ISSUE TITLE
Contract testing harness

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2430]
## Background
Currently, our contracts can be tested in the following ways:
* Rust contracts allow unit tests that allow testing contract without compiling it to Wasm. However, these tests do not allow cross-contract calls and do not include side-effects of generating receipts, like token transfer, account creation, staking, etc;
* AssemblyScript contracts can be tested by connecting to a running node, which makes tests slow and non-hermetic. @willemneal Is currently working on allowing tests to run by communicating with the runtime instead of the full node.

## Rationale
Since we are currently working on several important contracts like lockup/vesting, staking pool, voting, we want to be able to test these contracts including their interaction with other contracts (e.g. lockup/vesting contract interacting with the staking pool) and with the runtime (e.g. staking contract doing actual staking).

## Priorities
Therefore we want to implement a testing harness that would allow us to do the following, in decreasing priority:
1. For the Rust contracts, like lockup/vesting, staking pool, voting we want to be able to test cross-contract calls, runtime interactions, and gas metering, by using a standalone runtime;
2. We want to be able to do the same for AssemblyScript contracts;
3. The test harness should be runnable in the browser, i.e. the standalone runtime should be compilable to Wasm;
4. Integration tests and unit tests for contract should be using the same harness, e.g. unit tests can be using just a subset of the harness;
5. The harness should allow to iterate through all possible orderings of the receipt processing.

## Work items

Mainnet blockers:
- [ ]  `near-vm-runner-standalone` should include the `runtime` crate and should be split into `near-runtime-standalone` library and executable (can be done within the same crate);
- [ ]  lockup/vesting, staking pool, voting contracts should be using `near-runtime-standalone` and should have tests built with it.

Non-blockers:
- [ ] `near-runtime-standalone` should be published to crates.io and should not use rocksdb, requires some refactoring;
- [ ] `near-runtime-standalone` should be compilable to Wasm;
- [ ] `near-runtime-standalone` should be used in AssemblyScript.

## TBD

* To make `near-runtime-standalone` compilable to Wasm and executable from node.js/browser for AssemblyScript testing and gas estimation we need to find a way to abstract out the Wasm runtime such that it can be either Wasmer or V8. Unfortunately, the relation between the `near-runtime-standalone` and the Wasm runtime is not clear:
* With Wasmer `near-runtime-standalone` will have to own Wasmer and control its lifecycle;
* With V8, V8 will own `near-runtime-standalone` and control its lifecycle.

It is actually possible to have both types of the relationships. The proposed design is to hide Wasmer behind the trait in such way that when it we compile `near-runtime-standalone` to Wasm we inject into this trait the `wasm-bindgen` bindings to the host functions. However, we still need to think on this design.

**Comment by nearmax** [comment]
Assigning it to @frol since, AFAIU he is currently leading this effort, because it is mostly about refactoring.

**Comment by bowenwang1996** [comment]
We are in the process of redesigning the testing framework. This issue is no longer relevant.
