### ISSUE TITLE
Critical UX/DevX issues checklist

### ISSUE THREAD

**Issue by vgrichina** [near/nearcore#2518]
- [x] Tx status timeouts when transaction is missing https://github.com/nearprotocol/nearcore/issues/2488
- [x] Invalid transactions dropped from the pool don't have the error https://github.com/nearprotocol/nearcore/issues/2039
- [ ] nearlib sometimes sends 2 txns with the same nonce at once. 1 is guaranteed to fail.  https://github.com/near/near-api-js/issues/205
- [x] Access key allowance get charged for max allowed gas for tx instead what was spent https://github.com/nearprotocol/nearcore/issues/2523
- [ ] nearcore doesn't always return structured errors  https://github.com/nearprotocol/nearcore/issues/2572 https://github.com/nearprotocol/nearcore/issues/2536

**Comment by vgrichina** [comment]
not sure who checked 2488 checkbox, but let's mark only stuff that is in production as "fixed" for purposes of this tracker

**Comment by bowenwang1996** [comment]
@vgrichina that is fair, but can you verify that it works now on betanet?

**Comment by vgrichina** [comment]
@bowenwang1996 looks fine on betanet, except doesn't seem to be returning structured error:

```
[I] ➜ NODE_ENV=betanet near  tx-status DtPxTahaRwyG7pXYBUBQT5soFYjSJmrwnRsYfNkcQ1bb --accountId test_contract1586245860963186
Using options: {
  accountId: 'test_contract1586245860963186',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.nearprotocol.com',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.nearprotocol.com',
  helperUrl: 'https://helper.betanet.nearprotocol.com',
  hash: 'DtPxTahaRwyG7pXYBUBQT5soFYjSJmrwnRsYfNkcQ1bb'
}
Error:  TypedError: [-32000] Server error: Transaction DtPxTahaRwyG7pXYBUBQT5soFYjSJmrwnRsYfNkcQ1bb doesn't exist
    at JsonRpcProvider.sendJsonRpc (/Users/vg/.config/yarn/global/node_modules/near-api-js/lib/providers/json-rpc-provider.js:113:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/vg/.config/yarn/global/node_modules/near-shell/commands/tx-status.js:33:24
    at async Object.handler (/Users/vg/.config/yarn/global/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'UntypedError'
}
```

**Comment by bowenwang1996** [comment]
@vgrichina is this an issue on nearcore side or near-api-js side?

**Comment by vgrichina** [comment]
@bowenwang1998 on `nearcore` side:

```
[I] ➜ http post https://rpc.betanet.nearprotocol.com jsonrpc=2.0 method=tx params:='["CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g", "betanet"]' id=dontcare
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 162
Content-Type: application/json
Date: Mon, 27 Apr 2020 23:14:13 GMT
Server: nginx/1.14.0 (Ubuntu)

{
    "error": {
        "code": -32000,
        "data": "Transaction CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g doesn't exist",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

**Comment by frol** [comment]
@fckt Can you help us to set up the errors to be structured?

**Comment by bowenwang1996** [comment]
Looks like only the near-api-js one is still open. Closing this issue
