### ISSUE TITLE
Store Validator

### ISSUE THREAD

**Issue by Kouprin** [near/nearcore#2597]
Store Validator is a module like `state_dump` which takes the State, reads it into memory and checks lots of conditions which should be met in a valid State.
 This module may be executed:
 1\. Independently on arbitrary State to check is it valid or not (and where it's not valid).
 2\. While each python test execution, like refcount check.
 3\. In some CI / expensive tests written in Rust which needs such check (GC, i.e.).

*   <span class="error">[x]</span> Basic infrastructure, [https://github.com/nearprotocol/nearcore/issues/2649](https://github.com/nearprotocol/nearcore/issues/2649)
*   <span class="error">[x]</span> Major update that separates `store-validator` and `store-validator-bin` + lots of minor updates, [https://github.com/nearprotocol/nearcore/pull/2680](https://github.com/nearprotocol/nearcore/pull/2680)
*   <span class="error">[x]</span> Moving `store-validator` into chain module because of its usage of RuntimeAdapter. `store-validator-bin` is renamed to `store-validator`, [https://github.com/nearprotocol/nearcore/pull/2716](https://github.com/nearprotocol/nearcore/pull/2716)
*   <span class="error">[x]</span> Limiting time execution in Nightly, [https://github.com/nearprotocol/nearcore/pull/2808](https://github.com/nearprotocol/nearcore/pull/2808)
*   <span class="error">[x]</span> Error handling, according to @frol suggestion, [https://github.com/nearprotocol/nearcore/pull/2848](https://github.com/nearprotocol/nearcore/pull/2848)

The module is going to be built iteratively. We want to collect the list of all dependencies in data and extend the module by applying new conditions. After the list is done, it may be transformed into Spec.

Next steps:

*   <span class="error">[x]</span> Explore Python test failures and create issues for them
*   <span class="error">[x]</span> Enable testing Store Consistency in Nightly ([https://github.com/nearprotocol/nearcore/pull/2799](https://github.com/nearprotocol/nearcore/pull/2799))
*   [ ] Collect and add more conditions for consistency testing
*   [ ] Run binary after each python test automatically (not only while test executing), @mikhailOK suggestion ([https://github.com/nearprotocol/nightly/issues/5](https://github.com/nearprotocol/nightly/issues/5))

The full list of conditions:

*   <span class="error">[x]</span> ***head_tail_validity***: Checks that Chunk Tail <= Tail <= Head <= Header Head
*   <span class="error">[x]</span> ***block_header_hash_validity***: For every Block Header stored, Block Header hash is valid
*   <span class="error">[x]</span> ***block_header_height_validity***: For every Block Header stored, Block Header Height is not higher than Header Head
*   <span class="error">[x]</span> ***block_hash_validity***: For every Block stored, Block hash is valid
*   <span class="error">[x]</span> ***block_height_validity***: For every Block stored, Block Height is not higher than Head
*   <span class="error">[x]</span> ***block_indexed_by_height***: For every Block stored, it can be indexed by its Height
*   <span class="error">[x]</span> ***block_header_exists***: For every Block stored, Block Header is also stored
*   <span class="error">[x]</span> ***block_chunks_exist***: For every Block stored, there are all ShardChunks exist that are tracked and included to the Block ([https://github.com/nearprotocol/nearcore/pull/2716](https://github.com/nearprotocol/nearcore/pull/2716))
*   <span class="error">[x]</span> ***block_chunks_height_validity***: ShardChunks for current Block have Height Created not higher than Block Height
*   <span class="error">[x]</span> ***canonical_header_validity***: For each Block Hash stored on the Canonical Chain, we know that its Block Header is also available
*   <span class="error">[x]</span> ***canonical_prev_block_validity***: For each Block Hash stored on the Canonical Chain, if prev Block stored, it's also on the Canonical Chain and there are no Blocks in range (prev_height, height) on the Canonical Chain
*   <span class="error">[x]</span> ***chunk_hash_validity***: For every ShardChunk stored, ShardChunk hash is valid
*   <span class="error">[x]</span> ***chunk_tail_validity***: For every ShardChunk stored, Chunk Height Created is not lower than Chunk Tail
*   <span class="error">[x]</span> ***chunk_indexed_by_height_created***: For every ShardChunk stored, it's possible to indexing it by Height ([https://github.com/nearprotocol/nearcore/pull/2716](https://github.com/nearprotocol/nearcore/pull/2716))
*   <span class="error">[x]</span> ***chunk_of_height_exists***: For every ShardChunk Height stored, there is a ShardChunk exists ([https://github.com/nearprotocol/nearcore/pull/2716](https://github.com/nearprotocol/nearcore/pull/2716))
*   <span class="error">[x]</span> ***block_height_cmp_tail_final***: Makes sure there is no more than one Block which Height is lower than Tail and not equal to Genesis ([https://github.com/nearprotocol/nearcore/pull/2799](https://github.com/nearprotocol/nearcore/pull/2799))
*   <span class="error">[x]</span> ***trie_changes_chunk_extra_exists***: Checks the bijection between stored TrieChanges and ShardChunks data ([https://github.com/nearprotocol/nearcore/pull/2828](https://github.com/nearprotocol/nearcore/pull/2828))
     1\. - <span class="error">[x]</span> Block that TrieChanges reference to exists
     2\. - <span class="error">[x]</span> ShardChunk that TrieChanges reference to included into its Block
     3\. - <span class="error">[x]</span> ShardChunk is available
     4\. - <span class="error">[x]</span> ChunkExtra with same `block_hash` and `shard_id` exists
     5\. - <span class="error">[x]</span> ShardChunk is completely stored in Trie
     6\. - <span class="error">[x]</span> Prev State Root of ShardChunk should be equal to TrieChanges old_root (disabled due [https://github.com/nearprotocol/nearcore/issues/2843](https://github.com/nearprotocol/nearcore/issues/2843))
     7\. - <span class="error">[x]</span> State Root of ChunkExtra should be equal to TrieChanges new_root

*   <span class="error">[x]</span> ***outcome_by_outcome_id_exists***: Each record that is in ColOutcomesByBlockHash should be reachable in ColTransactionResult
*   <span class="error">[x]</span> ***outcome_id_block_exists***: Each Block that is in ColOutcomesByBlockHash should not be deleted
*   <span class="error">[x]</span> ***outcome_indexed_by_block_hash***: Each record in ColTransactionResult should be reachable in ColOutcomesByBlockHash
*   <span class="error">[x]</span> ***state_sync_info_valid***: Each ColStateDlInfos record should be consistent itself
*   <span class="error">[x]</span> ***state_sync_info_block_exists***: Each Block that is in ColStateDlInfos should not be deleted
*   <span class="error">[x]</span> ***block_info_exists***: Each record in ColBlockInfo should be reachable in ColBlock
*   [ ] ***block_info_block_exists***: Each record in ColBlock should be reachable in ColBlockInfo (no bijection found after State Sync)
*   <span class="error">[x]</span> ***epoch_validity***: Each Epoch in ColEpochInfo should exist
*   [ ] ***block_epoch_exists***: For each Block its Epoch id should be reachable in ColEpochInfo (not true in python tests)
*   <span class="error">[x]</span> ***last_block_chunk_included***: Block and ShardChunk that are in ColLastBlockWithNewChunk are reachable
*   [ ] For every Trie node, there is a ShardChunk which contains of the same data (discussed with @mikhailOK, will be implemented in [https://github.com/nearprotocol/nearcore/issues/2696](https://github.com/nearprotocol/nearcore/issues/2696))
*   <span class="error">[x]</span> ***state_header_block_exists***: For each State Header stored, there is a Block with same hash is available
*   <span class="error">[x]</span> ***state_part_header_exists***: For each State Part stored, there is a State Header stored, and id of State Part is not greater than num_parts in Header
*   <span class="error">[x]</span> ***chunk_tx_exists***: Txs included into Chunks are available in ColTransactions (disabled due #2930)
*   <span class="error">[x]</span> ***tx_refcount***: Txs' refcount are valid
*   <span class="error">[x]</span> ***tx_refcount_final***: Checks that there are no Txs that are not included to any ShardChunk
*   <span class="error">[x]</span> ***block_refcount***: Blocks' refcount are valid and there is no more than
*   <span class="error">[x]</span> ***block_refcount_final***: Checks that there are no Blocks that are not counted properly and number of Genesis Blocks is no more than one and number of Tail Blocks is no more that one

Any ideas welcome!

Infrastructure TODOs:

*   [ ] Refactor errors handling in Store Validator, [https://github.com/nearprotocol/nearcore/issues/2851](https://github.com/nearprotocol/nearcore/issues/2851)

**Comment by mikhailOK** [comment]
GC invariants:
- for every `Block` its height is `>= tail`
- for every `ShardChunk` there is a corresponding `Block`
- for every `ShardChunk` there are all trie nodes for its state root. There are no other trie nodes.
