### ISSUE TITLE
Thread-safe storage

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#2863]
List of things we need to run multiple threads

*   [ ] Add interface for creating read snapshots
*   [ ] Most readers from storage should use read snapshots. Reads that don't use snapshot should be resilient to transient errors of missing records
*   [ ] Locks for all writers to `ColState` (aka read + write transactions that need serializable isolation). Check if any other writers have this read + write behavior.
*   [ ] Check all our caches. Now they can be inconsistent with storage, make sure the mismatch can only go one way and does not break correctness.
*   [ ] Block production and GC will now share a lock. GC: support deleting one block at a time.

**Comment by SkidanovAlex** [comment]
Putting into Milestone 1 to track read snapshots for state.
Read snapshots for the rest of the storage is considered Milestone 2.

**Comment by Longarithm** [comment]
Looks like it wasn't under consideration for a long time. 

Reads during block processing are served from shared storage, writes happen at one main thread. State caches are guarded by locks, and for disk reads we rely on RocksDB consistency.

We learned how to use snapshots though, but for different reasons.
