### ISSUE TITLE
[Epic] Gain 100% confidence in Wasmer

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3188]
NEAR collective to be 100% confident in Wasmer+singlepass codebase. To gain this confidence we need to do the following:
* Have at least 2 people in NEAR collective fully understand Wasmer+singlepass codebase. This is not measurable and therefore it is not a goal. Therefore we define it through measurable subgoals:
  - [ ] Have these 2 people write exhaustive Wasmer+singlepass spec, potentially turn it into educational material, like a series of video lectures and/or posts. CC @mikedotexe ;
  - [ ] Have @olonho identify if there are any parts of Wasmer+singlepass that need security audit and audit them;
  - [ ] Have our own set of tests that test Wasmer on our CI. They should be written by us, to ensure that we indeed have in-house knowledge of Wasmer internals.

**Comment by matklad** [comment]
Actually, I think this is now done!

We have a much better understanding of wasmer2, we tested it heavily alone and against wasmer0. I don't think there are super-actionable steps we can take to achieve even more confidence medium term. 

So let's close this. wasmer2 is in master, so we'll get to test our confidence soon enough!
