### ISSUE TITLE
[Epic] Create process for proposing Nearcore changes

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#3250]
Currently, we are using the following process to propose the Nearcore changes:
* Someone submits NEP PR;
* Various Nearcore people review it at their convenience and have a discussion;
* At some point the discussion ends and it gets implemented.

There are the following issues with this approach:
* Too much information is figured out during the discussion, which is suboptimal in terms of time that discussion participants;
* The people who submit the proposal do not know when it is going to be reviewed and rejected/accepted/archived;
* The acceptance criteria is not clear, so it is not clear what kind of proposals are okay to submit;
* The owners of the review are also unclear, so the proposal might just get abandoned;

To improve this process we need to accomplish the following items:
- [ ] Make sure each Nearcore component has assigned owners;
- [ ] Make sure owners create acceptance criteria and contribution guidelines for each component (e.g. @frol  and @evgenykuzyakov were already thinking of the acceptance criteria for RPC and Transaction Runtime);
- [ ] Modify https://github.com/nearprotocol/NEPs#contributing to list the contribution guidelines for each component;
- [ ] Modify https://github.com/nearprotocol/NEPs#contributing to expand on "Build consensus and integrate feedback." part so it is clear for the contributors and component owners what is the flow, e.g.:
   1. When NEP is created owners of the affected components are assigned;
   2. Component owners take up to 1 week to review NEP and comment on NEP. If NEP does not follow the guidelines or does not pass the acceptance criteria it can be rejected immediately;
   3. Component owners might request more information, and the NEP owner might take up to 4 weeks to reply to it. Anyone else might provide missing information, too. If No missing information is provided within 4 weeks, it is archived.
  4. Steps 2-3 are repeated until the clarity is achieved and component owners decide whether to reject/accept/archive the proposal. 
  5. When proposal is accepted, its implementation is prioritized together with other work items. The implementation can also be done by external contributors. When implementation is merged NEP PR is merged too.

**Comment by bowenwang1996** [comment]
Does this specifically refer to protocol changes? For other changes we don't need to go through NEP.

**Comment by bowenwang1996** [comment]
Process proposed here https://gov.near.org/t/quality-control-for-protocol-api-changes/1941
