### ISSUE TITLE
Work on getting near-memory-tracker ready to be merged into near

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#3768]
This package currently has two main features implemented:
 1) adding header to each memory allocation, this allows tools that dump memory to determine how memory is used by Rust

 2) print warning/stack trace every time there is a memory spike on one of the Rust threads.

I also implemented an annotation, which allows to recursively count the size of all our Rust data structures, but I didn't include it in this change, to make the change smaller.

- [x] Extract allocator, from the separate larger change
- [x] Add per thread warnings about memory spikes
- [x] Print extra time spend by near-memory-tracker when performance_stats feature is enabled
- [x] Make sure this package works on mac, as well as linux
- [x] Move package to separate repo
- [x] Cleanup
- [x] Add printing memory usage per thread to stats printed by near-performance-metrics
