### ISSUE TITLE
TODO: Rewrite RouteBackCache code

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5316]
We should rewrite RouteBackTable. It's implementation may or may not be an issue.

TODO:
- [ ] add stats to see if the edge cases are happening in the production
- [ ] there is a logic, that chooses a peer with most messages, and removes 100 of them at once, It could be that better to remove choose the one most routes, remove one messages, and repeat this process 100 times
- [ ] datastructures can be simplified. We don't need one of the btrees, we can replace it if a `Deque` or double linked list.
- [ ] we don't report issues to Prometheus, or anywhere else
- [ ] we don't know for how long we keep routes inside, what's the the cache occupancy
- [ ] lack of benchmarks
- [ ] poorly optimized
- [ ] overcomplicated
- [ ] comments are confusing, don't describe what's going on
- [ ] lack of comments for methods.

**Comment by bowenwang1996** [comment]
> rewrite RouteBackTable

Could you elaborate why we need to rewrite it and what the plan is?

**Comment by pmnoxx** [comment]
@bowenwang1996 Ok, I added a plan
