### ISSUE TITLE
Tracking issue for workspace crate compliance

### ISSUE THREAD

**Issue by miraclx** [near/nearcore#5763]
<https://github.com/near/nearcore/pull/5724> implements crate compliance which introduced a set of rules every crate must uphold. And consequently, checks those rules against every PR ensuring they pass before being merged into master. To ensure uniformity and prevent unexpected behavior.

See <https://github.com/near/nearcore/pull/5724#issuecomment-989348386> for a list of the rules and their documentation. Feel free to chime in on the conversation, adding or removing rules in there as is deemed logical.

On that note, we have a series of current compliance violations with the current master as is highlighted on the [failing CI check](https://buildkite.com/nearprotocol/nearcore/builds/9824#af146b87-1a5d-40ab-8074-33752be92a41). And to ensure compliance, a series of PRs addressing each one would be opened, this is a tracking issue.

*   [X] Implement CI check for crate compliance. (<https://github.com/near/nearcore/pull/5724>)
*   [X] Ensure all crates are explicitly marked publishable or not. (<https://github.com/near/nearcore/pull/5764>)
*   [X] Ensure all crates specify a Minimum Supported Rust Version. (<https://github.com/near/nearcore/pull/5765>)
*   [X] Ensure all crates use the same rust edition. (<https://github.com/near/nearcore/pull/5766>)
*   [X] Ensure all crates with the workspace have the appropriate NEAR author. (<https://github.com/near/nearcore/pull/5772>)
*   [X] Ensure all * _non-private?_ * crates have the appropriate license. (<https://github.com/near/nearcore/pull/5773>)
*   [X] Ensure all * _non-private?_ * crates have the corresponding license files. (<https://github.com/near/nearcore/pull/5773>)
*   [x] #5849
*   [X] Ensure all * _non-private_ * crates appropriately link to the nearcore repository. (<https://github.com/near/nearcore/pull/5774>)

`?`: maybe this should be all crates and not just * _non-private_ * ones? (See <https://github.com/near/nearcore/pull/5724#discussion_r767006938> for the discussion)
