### ISSUE TITLE
Tracking issue for NEP-364: ed25519_verify host function

### ISSUE THREAD

**Issue by matklad** [near/nearcore#7567]
NEP: https://github.com/near/NEPs/pull/364
Implementation: https://github.com/near/nearcore/pull/7165

Stabilization PR: 

* [x] https://github.com/near/nearcore/pull/8098

Unresolved questions: 

* [x] [semantics for errors](https://github.com/near/NEPs/pull/364#issuecomment-1238147491)
* [x] correctly check signature length. The [current code](https://github.com/near/nearcore/blob/b315192e84d388671316deaa3a17ece9d0565fd1/runtime/near-vm-logic/src/logic.rs#L1151) is buggy: length is *either* length or or a flag to load from register. We should be checking the length of the vector we read from memory or register.
* [x] add tests for all error conditions we have inside the function (invalid sig, invalid pk, wrong length of either, empty message)
* [x] use realistic benchmark for cost computation. Today we use short message (32 bytes), not clear if that's the worst case
* [x] make sure that estimator checks the result (it's not clear whether we estimate failing or successful verification)
* [x] put the realistic costs into configuration

**Comment by akhi3030** [comment]
Do all of these need to be addressed before the feature can be stabilised?  If not, should we highlight which are essential for stabilisation?

**Comment by matklad** [comment]
Yes, they all are mandatory for the standard of quality we want to maintain.

**Comment by matklad** [comment]
cc @blasrodri as the author of the original impl

**Comment by matklad** [comment]
I guess another useful thing to have before stabilization is to use this _nightly_ function in some contract on the beta net. So, if someone's already using this, please ping this issue, even if you don't have any problems )

**Comment by matklad** [comment]
This is more or less ready for stabilization I think, though

> I guess another useful thing to have before stabilization is to use this nightly function in some contract on the beta net. So, if someone's already using this, please ping this issue, even if you don't have any problems )

would still be a nice sanity check

**Comment by jakmeier** [comment]
@blasrodri to get this into the release pipeline, we still need a stabilization PR that removes all the feature flags. Otherwise this stays in nightly (betanet) forever.

**Comment by blasrodri** [comment]
> @blasrodri to get this into the release pipeline, we still need a stabilization PR that stabilizes the feature flag and removes some of the `#[cfg]` that's no longer needed. Otherwise this stays in nightly (betanet) forever.

got it! will take care of it :)

**Comment by blasrodri** [comment]
I have made this one some time ago:
https://github.com/near/nearcore/pull/8098

**Comment by jakmeier** [comment]
Oh, sorry I missed that completely :(
I will review it and once it's merge to master, it will go to testnet with the next testnet release.

**Comment by jakmeier** [comment]
Closing this as the feature has been merged to master. (If anything comes up while testing on testnet, we can always reopen.)
