### ISSUE TITLE
Tracking issue: Leftover after Sweatcoin launch

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#7634]
This issue tracks technical debt and leftover work after we prepared everything for the Sweatcoin launch.

Sweatcoin launching on mainnet has been a challenge for the network, as it is the first smart contract with consistently high IO workload. 
To reduce risks on the launch, we tested the launch thoroughly on testnet with high workloads. We found that increased IO throughput could be a problem in some scenarios.

We have taken several steps to reduce the risk in the short term, and we have long-term plans to make IO more efficient. The long-term solution is to implement flat-storage, which is already tracked in #7327. Short-term solutions taken are mainly #7429, #7590, #7620.

Left-over work:

- [ ] Observe mainnet IO traffic during release window for nearcore version 1.29
- [ ] Enable account and access key prefetching by default
- [ ] Remove hacky argument based prefetcher
- [ ] Cleanup cache configuration code

**Comment by akhi3030** [comment]
AFAIK, further work on this is blocked till we have finished flat storage work.

**Comment by jakmeier** [comment]
just added another issue for cleaning up test data from testnet
