### ISSUE TITLE
Testnet retrospective 2022-10

### ISSUE THREAD

**Issue by akhi3030** [near/nearcore#7892]
Below is a list of tasks that we identified as blocking the retrospective for the testnet outage that occurred on Oct 2022.

- [ ] https://github.com/near/nearcore/issues/7865
- [x] https://github.com/near/nearcore/issues/7860
- [x] https://github.com/near/nearcore/issues/7842

**Comment by akhi3030** [comment]
CC: @mm-near, @mzhangmzz
