### ISSUE TITLE
Integrate `near/wasmer` into `near/nearcore`

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#7983]
Historically, the VM implementation we relied on to execute the WASM code in the past was a third party project. At some point, we found ourselves wanting to make some adjustments to the implementation, so the project ended up being forked into [near/wasmer](https://github.com/near/wasmer). At that time we still thought we could develop this collaboratively with the upstream, merging changes back and forth. This worked for a little while, but eventually our implementations have diverged sufficiently that integrating changes in either direction stopped making much sense.

With `near/wasmer` being a very nearcore specific implementation of the WASM VM, there is no longer a clear reason to keep these two repositories separate. With our otherwise mono-repository focused workflows and tooling, keeping these two very closely related repositories separate is actually a chore we don’t really want, nor have the resources, to keep up with.

This is a tracking issue of tasks we need to complete in order to fully integrate the `near/wasmer` repository into `near/nearcore`.

* [ ] Remove any public interfaces exposed by `near/wasmer` not directly used by the `near-vm-runtime`;
* [ ] Merge the `near/wasmer` code into this repository (optionally, preserving the history);
    * [ ] Make sure licensing story does not change – wasmer is licensed under `MIT`, `nearcore` is `MIT OR Apache-2.0`. The merged code must retain the original license, and it must be made obvious to anybody looking (i.e. make sure descriptions of licensing do call out this exception universally.)
* [ ] Make sure the CI runs `near/wasmer` tests, that the tests are not flaky and relatively fast. 
* [ ] Copy over the entries in `near/wasmer`'s issue tracker;
* [ ] Adjust `near-vm-runtime` and other tools to refer to the local copy of the code;
* [ ] Archive the original repository.

**Comment by nagisa** [comment]
This has been addressed -- near_vm is in our repository now.
