### ISSUE TITLE
Tracking issue for codebase modularization and other dev velocity improvements

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#8153]
General theme: split chain into logical components; have testing for each logical component.

Some items we have come up with so far (many of these need further brainstorming)

For those who have access: [link to the VC where we discussed this issue](https://drive.google.com/file/d/1OubPxnEVmaZl9zPP9UsTDHC4MlXixRfm/view?usp=sharing)

- [ ] Split ChainStore, so we can split Chain
- [ ] Add detailed documentation as comments on top of every Chain and Client function.
- [ ] Split Client
- [ ] Improve the composability of testing utils, such as TestEnv and the intimidating setup_mock_all_validators, so we can write more granular tests and be more precise about how tests are set up.
  - [x] https://github.com/near/nearcore/issues/8190
- [ ] Export more debugging info for partial encoded chunks handling
- [ ] Have a clearer API for working with the chain topology (e.g. no "head", "header_head", "head_header" business); fix issues related to incorrect/inaccurate use of chain topology (#8154). Have a isolated component just to manage topology.
- [x] Finish ShardsManager refactoring to move it onto separate actix (#7662)
- [ ] #8324
- [ ] Finish EpochManager refactoring (#6910)
- [ ] Have a proper debug UI project (#8356 )
- [x] #8191

**Comment by mzhangmzz** [comment]
Adding other ideas here:
- finish the EpochManager refactor https://github.com/near/nearcore/issues/6910
