### ISSUE TITLE
add integration tests for meta transactions

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8467]
Goal: Assure full test coverage of meta transactions.

We already have unit test that trigger all of the potential errors, except for the error about nested delegate actions.

Additionally, I propose to add tests on the `trait User` abstraction level, basically end-to-end as far as nearcore is concerned. There, I would like to see one test for each type of action. And a couple of common scenarios.

- [x] Remove nested delegate actions error (#8538)
- [x] Extend `trait User` to execute meta transactions (#8551)
- [x] Add test for CreateAccount (#8568)
- [x] Add test for DeployContract (#8559)
- [x] Add test for FunctionCall (#8551)
- [x] Add test for Transfer (#8551)
- [x] Add test for Stake (#8559)
- [x] Add test for AddKey (#8559)
- [x] Add test for DeleteKey (#8559)
- [x] Add test for DeleteAccount (#8559)
- [x] Test scenario for fungible token transfer (#8564)
- [x] Test for onboarding a user with an implicit account but no tokens (#8568)
- [x] Test when executing a meta transaction with a function call access key and allowance (instead of full access key) (#8570)

**Comment by jakmeier** [comment]
I think now that #8538 has removed the nested delegate error, we don't really need a test for it.

We could only add a test for deserialization to fail. That seems to be an overkill for integration tests. We already have unit tests in `core/primitives/src/delegate_action.rs` that check (de-)serialization works as intended.

=> I will mark that point as done.

**Comment by jakmeier** [comment]
All merged! :tada:
