### ISSUE TITLE
meta tx acceptance by a node depends on the protocol version

### ISSUE THREAD

**Issue by jakmeier** [near/nearcore#8468]
the current solution uses different borsh deserialization at compile-time depending on the protocol feature flag, before we can stabilize the feature we need to change it to runtime protocol feature checks

**Comment by jakmeier** [comment]
This has the potential to be a lot of work.

DelegateAction borsh serialization is indirectly part of:
- Receipt
- Transaction
- ChunkProofs / ChunkState etc (challenge related types)
- Blocks (through challenges)
- ShardChunk (V1/V2)
- ShardStateSyncResponseHeader (V1/V2) + ShardStateSyncResponse(V1/V2)
- StateChangesForSplitStates
- PeerMessage (SignedTransaction,Block,RoutedMessage::RoutedMessageBody::TxStatusResponse)

Each of these types has presumably a good reason to require borsh.

Adding an enum variant is backwards compatible for the parsers, but we also need forward compatibility during the upgrade, and proper version handling on the logical layer using these types.

I am currently figuring out what all the requires steps are.

**Comment by jakmeier** [comment]
I think I have looked at all cases where meta transactions could slip in. Most cases don't need a special handling and those that need one I have now addressed. So I will close this issue as done, with my final analysis on each case below:

- [x] **Runtime**: We capture meta transactions sent on an older protocol version, which is now done and tested in #8477. This makes all uses of meta transactions in `Transaction` / `Receipt` / `ShardChunk` invalid. New binaries will be able to parse them but fail in validation. Old binaries will not even be able to parse them and thus ignore them.
- [x] **Challenges** / **Proofs**: An honest validator will never include a challenge at this point. `process_challenge` completely ignores the content of challenges. (#2445)
But we must also cover for malicious validators. In `validate_header` we check that every block header contains only an empty challenges root. If any block producer tries to include challenges in the block anyway (including meta transactions or not) then it will not be included because `Block::check_validity` will fail for all honest validators. Therefore it's okay for old binaries to just drop such blocks as parsing errors.
- [x] **PeerMessage**: New binaries should not use meta transaction until the protocol upgrade finished, but they may accept such transaction into the pool and try to apply them. That's okay, it will fail verification before they get recorded on chain.
Old binaries will drop incoming messages if they receive them mistakenly from new binaries, which is almost as good as dropping them during validation.
- [x] **State Sync**: An honest validator will never include a meta transaction in a state part before the protocol upgrade. Thus, old binaries can just drop them as parsing errors if they ever receive one. But what about new binaries? They might receive a state part with a meta transaction from a malicious peer and they could parse it. But it will fail the merkle proof validation, so it will not be accepted either.
