### ISSUE TITLE
With 1 million near.social transactions per day, the p99 transaction latency is less than 5 seconds

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#8488]
This is a tracking issue for the work associated with the NI-KR-1380 key result.

Our goal is to support a workload of 1 million daily transactions generated by near.social users such that more than 99% of these transactions go from `near call` to the result of execution in less than 5 seconds flat.

# Tasks

* [ ] https://github.com/near/nearcore/issues/8592
* [ ] https://github.com/near/nearcore/issues/8529
* [ ] Create a representative benchmark to generate and evaluate this sort of load. In particular we aren’t quite sure whether this is a problem at all, and if it is, where the actionable fixes might be.
* [ ] If not already true, improve the codebase so that this is true…

**Comment by nagisa** [comment]
Disclaimer: I’m entirely ignoring any flat time overhead on operations such as converting a transaction to a receipt and such. The focus is entirely on the execution time, as it is easy to reason about.

Evaluating basic numbers: looks like `@near.social:set` function call takes about 10-11Tgas today(?)

With 5Pgas in 5 seconds, assuming no under- or over-charging, no additional sources of latency and 100% utilization of resources, we can fit about 460 such transactions within the 5 second latency limit. If we’re looking at the load that is consistent and evenly spread over a period of slightly more than 3 hours, we can easily execute 1M transactions within the requirements on latency, no problem there. In practice, the load is rarely evenly, consistently or predictably spread over a time period.

Perhaps an easiest way to demonstrate it is with the following (semi-)fictional scenario. Lets say we buy out a prime-time ad slot for ~~Twitter~~near.social during one of the super-bowl (american football) games. ~~Twitter~~near.social isn’t otherwise very popular, but during this 3-hour-or-so game we expect to reach the 1 million transaction count goal because our ad turned out real great and there’s no way people will post their thoughts elsewhere but on our network. The network is able to support just about 996k `@near.social:set` calls over these 3 hours, so we'd be in a pretty nice spot here. *If* the load pattern was consistent. But that isn’t the case at all. People will only post status updates when _interesting_ (or uninteresting, I guess) things happen during the game: there's a goal, game is won by the more popular team, a [break is called for](https://en.wikipedia.org/wiki/TV_pickup), etc.

I guess what I'm trying to say is that this KR is somewhat ill defined from the execution time perspective unless we also specify the expected load pattern.

Repeated reminder is that I haven’t yet considered other constant overheads of getting from `near call` to to a transaction result… If those happen to be consistently around or more than 5s already, that's an issue to look into and to fix.

**Comment by jakmeier** [comment]
> I guess what I'm trying to say is that this KR is somewhat ill defined from the execution time perspective unless we also specify the expected load pattern. 

Fair point! I discussed it with @akhi3030 and we think we can just assume a uniform distribution of requests for now. That's the easiest way to technically meet the requirements stated by the KR and it's probably also what the intention behind the KR was. That might not reflect the actual usage of near.social but it's a helpful first step. If it turns out we can easily support 1M transactions that way, then we can experiment with higher throughput and/or add some more interesting request distributions.

> Disclaimer: I’m entirely ignoring any flat time overhead on operations such as converting a transaction to a receipt and such. The focus is entirely on the execution time, as it is easy to reason about.

For the high level analysis, that makes sense. But just to be clear, for the benchmark we will want to include all this constant overhead, right? It feels like one of the more important details to capture in a benchmark, precisely because they are hard to reason about.

**Comment by nagisa** [comment]
> For the high level analysis, that makes sense. But just to be clear, for the benchmark we will want to include all this constant overhead, right?

Correct, I’m just not entirely clear on the deets of this, as evidenced by some of my questions on Zulip. I filled https://github.com/near/nearcore/issues/8529 to get a clear view of _that_ first.

**Comment by jakmeier** [comment]
I decided to create a new issue for this quarter's benchmarking, as the stated goal is quite different after all. https://github.com/near/nearcore/issues/8999

But as I am working on that, I might have some updates to add this issue regarding latency related results and unexpected performance oscillation

**Comment by nagisa** [comment]
Triage: we should probably either close this or make a call that we will want to return to this (e.g. as part of the renewed push towards benchmarking.) An interesting detail is that we have talked about latency again a few times recently, but in the context of other kinds of workloads.

**Comment by akhi3030** [comment]
Agreed.
