### ISSUE TITLE
Tracking issue for "The public interface of client.rs/chain.rs/client_actor.rs is clearly defined and documented"

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#8524]
- [x] #8525 
- [ ]  Figure out a plan for separating Client and Chain.
- [ ] All functions in client.rs and chain.rs are documented.
- [ ] Client.rs and chain.rs are split to files with no more than 1000 lines.

**Comment by walnut-the-cat** [comment]
Please add issue ID for the 2nd-4th items :)

**Comment by robin-near** [comment]
They are P1... Can I do them later I hate this tool 🥺

**Comment by soonnear** [comment]
Part of #8153
