### ISSUE TITLE
Tracking issue: We can set safe gas costs for Flat storage deployment 

### ISSUE THREAD

**Issue by akashin** [near/nearcore#8550]
This is tracking issue for the work associated with NI-KR-1450 key result.

We want to have a mechanism that would allow to set safe gas costs for storage operations during deployment of Flat Storage, while still maintaining compatibility with older contracts.

Work that needs to be done to achieve this:
- [x] https://github.com/near/nearcore/issues/8032
- [x] https://github.com/near/nearcore/issues/8006
- [x] Introduce Compute Weights for Storage operations

**Comment by akashin** [comment]
Compute Costs have been submitted and stabilized, so I declare this issue resolved. The future work on actually setting compute costs for storage is tracked in https://github.com/near/nearcore/issues/8791, so I'm going to close this issue.
