### ISSUE TITLE
Rate limiting for incoming transactions

### ISSUE THREAD

**Issue by akashin** [near/nearcore#8878]
This is a tracking issue for work on limiting the footprint of transactions in the transaction pool.

```[tasklist]
## Ideas to explore
- [ ] https://github.com/near/nearcore/issues/3284
- [x] Don't accumulate transactions on RPC nodes (https://github.com/near/nearcore/pull/8965)
- [x] Out of scope: Rate limit sources that DDOS the system
- [ ] https://github.com/near/nearcore/issues/8879
```

**Comment by akashin** [comment]
Additional questions from Yoon:
- [ ] Does the user know whether their transaction was accepted to the transaction pool?
- [ ] If the transaction fails validation, at which point will the error be returned to the user?

**Comment by akashin** [comment]
There was some work on not accumulating transactions on RPC nodes https://github.com/near/nearcore/pull/6713 that was ultimately rolled back https://github.com/near/nearcore/pull/6827. Full context is in https://docs.google.com/document/d/1tZvXyaQeFSMUY-IyFtU_vjkkMiKco1_nLRtGzzBERMo/edit#
I'll look into ways to resolve the identified issues.

**Comment by akashin** [comment]
My high-level summary so far is that the client code (e.g. jsonrpc) is not resilient to dropping transactions from the transaction pool, which would make this task more complicated as we can't rely on simple time-based garbage collection policies. We'll need to explore two avenues:
- Modify clients to be resilient to transaction dropping
- Admission control at the moment when transaction is submitted that is based on current size of the pool

**Comment by akashin** [comment]
We now have a transaction pool limit implemented and the default of 100 MB will be enabled in the next release.

The last remaining item https://github.com/near/nearcore/issues/8879 turned out to be less important, so we will do it later when we actually hit the conditions described there (right now 100 MB is quite a lot of transactions).

Thus, I will mark this as done for the purpose of Local Congestion Control.
