### ISSUE TITLE
Create dashboards tracking key congestion metrics

### ISSUE THREAD

**Issue by akashin** [near/nearcore#8880]
This is a tracking issue for work on tracking and exposing key congestion metrics.

It’s essential to understand the key characteristics and patterns of the load on the blockchain to make a good decision about the design to deal with the congestion problem. We should build dashboards tracking key congestion metrics.

```[tasklist]
# Metrics to track
- [x] Length of delayed receipts queue per shard
- [x] Distribution of wait and processing times for accepted transactions (grouped by number of receipts)
- [x] Size (count, gas, bytes) and age of transactions in the transaction pool
- [x] Number of postponed receipts per shard
```

We can extend http://go/grafana-undercharging to track these metrics.

**Comment by akashin** [comment]
Comment from Jakob:
This seems to be easy to add and would be useful for other projects in this space.

**Comment by akashin** [comment]
I've finished the ad-hoc analysis of congestion metrics, the results can be found in [this doc](https://docs.google.com/document/d/1q9MrrmDthzHCFsry30Gni_-IbjniozQe4H_M1WGNw48/edit#bookmark=id.9qbi4zh4yxwu) and the code to reproduce the analysis is in https://github.com/PagodaPlatform/congestion-analysis.

The next step that I'll do over the next few weeks will be to collect feedback on this analysis to understand whether this data is useful and decide whether we want to invest in better tooling in this space (steps from https://github.com/near/nearcore/issues/8880#issuecomment-1514329359).

**Comment by akashin** [comment]
I've moved all the tasks related to long-term transaction trend metrics to https://github.com/near/nearcore/issues/9146, to decrease the scope of this issue only to the local node metrics necessary to debug different congestion scenarios (for example https://github.com/near/nearcore/issues/8920).

I will add the relevant metrics to the [first comment](https://github.com/near/nearcore/issues/8880#issue-1653652930) of this issue.

Implementation-wise, my first hunch is to extract these metrics during chunk processing (e.g. [delayed receipt count](https://github.com/near/nearcore/blob/d568022083b67265f4f1c92adb6712f85a9b2f1e/runtime/runtime/src/lib.rs#L1300) here) and export them as a part of [`ApplyResult`](https://github.com/near/nearcore/blob/d568022083b67265f4f1c92adb6712f85a9b2f1e/runtime/runtime/src/lib.rs#L1485) to log them outside, but maybe there is more elegant way.

**Comment by akashin** [comment]
Quick note, "Distribution of wait and processing times for accepted transactions (grouped by number of receipts)" metric is a lower priority as we can see that on Locust for now, but it will be needed eventually for mainnet. It will likely require the refactoring described in https://github.com/near/nearcore/issues/9060.

**Comment by jakmeier** [comment]
In  https://github.com/near/nearcore/pull/9188 I added some more metrics I deemed necessary. I added them to the task list here for completeness.

Also, I have added new panels to http://go/grafana-undercharging. They only show something for `testnet-experimental`. Here a few examples how it looks when data is available:

Aggregated compute usage:
![image](https://github.com/near/nearcore/assets/6342444/465853c0-c9f6-4e45-b61c-08c5df86bb83)


Per shard gas vs compute:
![image](https://github.com/near/nearcore/assets/6342444/06200427-5454-4991-b339-da7d05ce6c9c)

Per shard distribution of sources:
![image](https://github.com/near/nearcore/assets/6342444/e24388ed-7d01-4ce1-aba1-57e80f24dbc5)


Per shard size in bytes used for transactions:
![image](https://github.com/near/nearcore/assets/6342444/b0d462bd-3abf-4102-bf48-e9bd152bba91)

**Comment by jakmeier** [comment]
cc  @akashin feel free to move around, change, or even just delete stuff that I've added, if you think it doesn't fit into this board. I'll probably end up creating add a more debug oriented dashboard anyway, to include more details (more histograms, less avg(sum) aggregated graphs).
