### ISSUE TITLE
Stabilize FS read on Mainnet with improved performance

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#8893]
Core team Q2'2023 initiative.

Deploy flat storage for reads on mainnet and improve its performance further.

### Milestones

- [x] https://github.com/near/nearcore/issues/8827
- [ ] ~https://github.com/near/nearcore/issues/8826~
- [ ] ~https://github.com/near/nearcore/issues/8243~
- [ ] ~https://github.com/near/nearcore/issues/8741~

**Comment by Longarithm** [comment]
Example of node with flat storage: https://nearinc.grafana.net/d/zzGDUdcnk/debug-metrics?orgId=1&var-chain_id=testnet&var-role=logunov-testnet&var-node_type=All&var-node_id=logunov-testnet-fs-3&var-shard_id=All&viewPanel=18&from=1679006982909&to=1681140641446

Testnet RPC node with flat storage running for ~1 month without any performance degradation.

**Comment by Longarithm** [comment]
Flat storage was included into testnet release cut: https://github.com/near/nearcore/releases/tag/1.34.0-rc.1

**Comment by walnut-the-cat** [comment]
Main release is completed and other ones are postponed due to priority.
