### ISSUE TITLE
Initiative: Align on solution to improve storage write performance

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#8895]
Core team Q2'2023 initiative.

`storage_write` requires up to `2 * key.len()` **blocking** random State **reads**. This is the reason why we have storage undercharging, rely on prefetching for shard 3 and are uncertain if we meet requirements for near.social. While it was more or less straightforward to improve for reads (see https://github.com/near/NEPs/blob/master/neps/nep-0399.md), writes require more strategic approach. So our goal here is **just** to evaluate ideas that can drastically improve write performance and decide which of them is overall the best.

### Milestones

- [ ] Define relevant metrics to measure performance
- [ ] list out feasible solutions to improve write performance
- [ ] evaluate each options and align on the solution
- [ ] [Stretch] have PoC showing validity of the solution
- [ ] [TBD] Sweatcoin prefetcher removal (can happen after write implementation is in place)

**Comment by Longarithm** [comment]
I intentionally don't create sub-issues for now because we didn't agree on the approach yet, let's do it when plan becomes more clear.

**Comment by Longarithm** [comment]
As we have more time free of #8899, we started to move forward here.

* I listed some ideas we already have on the plate ([Zulip](https://near.zulipchat.com/#narrow/stream/313099-pagoda.2Fstorage/topic/state.20storage.20ideas/near/361146153))
* After several meetings, we agreed on exact next steps ([Zulip](https://near.zulipchat.com/#narrow/stream/313099-pagoda.2Fstorage/topic/weekly.20storage.20meeting/near/360822370)).

They include building general benchmarking tool, investigating RocksDB performance and background prefetching of trie nodes. Maybe we'll create some new issues to track.

**Comment by walnut-the-cat** [comment]
We have not spent too much time on evaluating different options, but just came up with the one making most sense for us.
