### ISSUE TITLE
Improve scalability of TIER2 Routing table

### ISSUE THREAD

**Issue by saketh-are** [near/nearcore#8904]
Core team Q2'2023 initiative.

To improve scalability of the TIER2 network, we will implement a distributed routing protocol in which each node does not possess information about the full network topology. Instead, each node will:

- Store and broadcast a shortest path tree connecting it to all routable targets in the network, and
- Verify and store the shortest path trees broadcast by its direct neighbors, using them to compute its own shortest path tree

The proposed changes also eliminate the possibility of memory exhaustion due to fake edges broadcast by malicious nodes.

[Design Document](https://docs.google.com/document/d/192NdoknskSLavttwOZk40TSYvx2R1if4xNZ51sCNFkI/edit#heading=h.j4e0bgwl42pg)

To satisfy upgradeability constraints, we will need:
- V1: Current state, supports just SyncRoutingTable
- V2: Supports both SyncRoutingTable and SyncRoutingTableV2, continues to route over the old protocol
- V3: Supports just SyncRoutingTableV2, routes over the new protocol

### Milestones
- [x] Implement V2 by adding the new routing protocol and messages between nodes to support it.
- [ ] Deploy V2, then verify that network reachability and path lengths under the new protocol match the old
- [ ] Implement V3 by removing the old routing protocol and dropping messages associated with it.
- [ ] Deploy V3
- [ ] Update documentation of network routing protocol in NEAR [nomicon](https://nomicon.io/NetworkSpec/RoutingTableExchangeAlgorithm)

**Comment by walnut-the-cat** [comment]
Almost done. Will aim to merge the code in by July 14th.

**Comment by saketh-are** [comment]
Closing this issue because we have completed implementation and have a separate issue #9293 for tracking the rollout.
