### ISSUE TITLE
Tracking issue for RoutingTable V2 rollout

### ISSUE THREAD

**Issue by saketh-are** [near/nearcore#9293]
- [ ] Design and implement metrics needed to verify performance of V2 routing protocol
- [ ] Release V2 to testnet and verify metrics
- [ ] Test and release version in which V2 is the default path and V1 shadows
- [ ] Deprecate V1
- [ ] Deprecate tombstone edges

**Comment by walnut-the-cat** [comment]
Please note that this tracking issue is long standing and won't close until we fully deprecate routing table v1.

09/27
* Still waiting for 1.36 rollout. 
* Saketh found another issue that can be problematic with v2 rollout. The solution is identified and Saketh plans to implement and include it in 1.36 ([ref](https://docs.google.com/document/d/15A_Hv3EnyivBIbSrBpVBAvO_AxvahQwFSuC1tYpTtm0/edit?usp=sharing))
