### ISSUE TITLE
RocksDB performance improvement

### ISSUE THREAD

**Issue by jbajic** [near/nearcore#9297]
## Introduction
The goal of this issue is to set up a workflow basis for tracking RocksDB configuration improvements and to reliably measure them.

## Tasks

- [x] Create a state-perf tool @pugachAG #9276
- [ ] Test the idea for reducing block size
- [ ] Test the idea for separating block from index and filter cache
- [ ] Improve the size of block cache size for the `State` and `FlatState` columns
- [ ] Expose additional RocksDB metrics to prometheus
- [ ] Setup a node on which to observe new RocksDB configuration parameters
