### ISSUE TITLE
Tracking issue: Fuzzing necessary groundwork

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#9310]
In order to make everything work well easily, we need to find a way to integrate cargo-bolero (for private items fuzzing) with clusterfuzz (for continuous fuzzing). Ideally PRs to bolero and clusterfuzz will land, but we can always use a fork meanwhile. The clusterfuzz PR is cosmetic.

```[tasklist]
### Tasks
- [ ] https://github.com/camshaft/bolero/pull/161
- [ ] https://github.com/camshaft/bolero/pull/162
- [ ] https://github.com/camshaft/bolero/pull/163
- [ ] https://github.com/google/clusterfuzz/pull/3216
- [ ] https://github.com/near/clusterfuzz/pull/4
- [x] Deploy https://github.com/near/clusterfuzz/pull/4
- [ ] https://github.com/near/finite-wasm/pull/70
- [ ] https://github.com/near/finite-wasm/pull/71
- [ ] https://github.com/near/finite-wasm/pull/72
- [ ] https://github.com/camshaft/bolero/pull/176
- [ ] https://github.com/camshaft/bolero/pull/177
```

**Comment by Ekleog-NEAR** [comment]
The last non-completed change here is just a cosmetic change in clusterfuzz, and google doesn’t seem very reactive. Closing this issue, as the work here is basically done :)
