### ISSUE TITLE
August 2023 milestone: Fuzzing necessary groundwork

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#9412]
- [x] Get all PRs listed in https://github.com/near/nearcore/issues/9310 in a state where upstream has no outstanding nits
- [x] Update our infrastructure so that we can start working on new fuzzers without waiting for upstream projects to merge and release
- [ ] (Aspirational) Start working on fuzzers for host functions

**Comment by Ekleog-NEAR** [comment]
Our infrastructure is now running with our forks of bolero (for finite-wasm) and clusterfuzz, though the PRs have landed yet. So the non-aspirational part of the milestone is now complete :)

**Comment by Ekleog-NEAR** [comment]
Actually I just thought that I can use this to also use this issue to document the other stuff (outside of what’s listed here) I’ve worked on during August, so that it’s easier to find than in the zulip weekly sync meeting history only:
- Switched finite-wasm to using cargo-bolero on clusterfuzz
- Madrid offsite
- Hacked on zkwasm
- Enabled github merge queues on nearcore
- Worked on CI RTT, thought of our dual use of buildkite and GHA
- Thought about our security release process
- Discussed the best communication patterns with Hacken

**Comment by akhi3030** [comment]
This is a cool idea.  Maybe others in @near/contract-runtime might be interested in doing something similar as well.
