### ISSUE TITLE
🔷 September 2023 milestone: Generic security work & putting fuzzing in production

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#9486]
Previous milestone: https://github.com/near/nearcore/issues/9412

#### Generic security work

- [x] Define a long-term plan for security in nearcore
- [x] Define interview guidelines for security engineers
- [x] Define a proper security release process
- [x] (Aspirational) Start drafting a threat model for nearcore

#### Fuzzing (related: https://github.com/near/nearcore/issues/9310)
- [x] Investigate the fuzzer failures we have been seeing on wasmtime
- [x] (Aspirational) Migrate nearcore to cargo-bolero-based fuzzers
- [ ] (Aspirational) Start working on fuzzers for host functions

**Comment by Ekleog-NEAR** [comment]
Currently done this first half-month:
- Wrote down a plan for the ~next year of security work
- Defined new interview guidelines for our security engineer interview process
- Started running 1:1’s about nearcore security, to define a threat model
- Started working on an improved security release process

Also done this first half-month, outside of the planned milestone:
- Helping Hacken with the security audit
- Looked at another attack that came in against our CI system, thinking of ideas to improve that domain
- Made progress on the work carrying over from #9412
- Had a look at zk proofs, and how to implement them with cranelift
- Code reviews, some big and some less big
- Gave four interviews
- Tried to move politics especially wrt. countries not listed despite the timezone being fine

**Comment by Ekleog-NEAR** [comment]
Done in the second half-month:
- Refined the interview guidelines for our security engineer interview process, after running the interview
- Submitted improvements to our security release process, currently awaiting a first review by @gmilescu 
- Started interviewing people to initiate threat modeling
- 
- Investigated the fuzzer failures that we saw on clusterfuzz regarding wasmtime. They are due to a clusterfuzz misconfiguration
- Submitted nearcore#9602 and nearcore#9603, that migrates nearcore to cargo-bolero-based fuzzers, thus getting us ready for easily adding new fuzzers

Also done this second half-month, outside the planned milestone:
- Chatted with Pagoda’s security team on figuring out security tooling for nearcore
- Finished up the last remaining work from nearcore#9310
- Submitted a few other bolero improvements that we can use
- Code reviews, some big and some less big. Especially focusing on the in-memory trie idea
- Fiddled with github settings so that merge queues work better with our workflow
