### ISSUE TITLE
Implement in-memory trie

### ISSUE THREAD

**Issue by robin-near** [near/nearcore#9511]
```[tasklist]
### Tasks
- [x] Prototype in-memory trie loading
- [x] Prototype in-memory trie modification
- [x] Prototype in-memory trie write-back to disk
- [x] Implement production-ready code for in-memory trie loading
- [x] Implement production-ready code for in-memory trie modification and writeback
```

**Comment by walnut-the-cat** [comment]
Prototype is complete and remaining work will be focusing on the following items
* GC implementation
* Making sure there is no memory leak
* Clean up/refine code as it’s currently in prototype stage
* Support in memory trie with specific shard (mid-term storage performance mitigation)


In October, we expect completion of the project along with the following items:
* Complete implementation of in-memory trie
* partial in-memory trie ([ref](https://docs.google.com/document/d/1TzMENFGYjwc2g5A3Yf4zilvBwuYJufsUQJwRjXGb9Xc/edit#heading=h.g1xqke6gf3ys))

**Comment by robin-near** [comment]
Prototype is all complete except GC needs further validation. See https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/putting.20all.20state.20in.20memory for context.

Code for loading is checked in, code for modification, GC, and writeback are pending.
