### ISSUE TITLE
Prepare a 6 month roadmap for ZK WASM project

### ISSUE THREAD

**Issue by akashin** [near/nearcore#9513]
To make sure we can effectively execute the vision of fast ZK proofs for WASM programs and further integration into NEAR blockchain we want to agree on the roadmap of how we plan to get there. To finalize the roadmap we need:

```[tasklist]
- [x] Select WASM workloads that we want to support well
- [x] Set performance targets (proof size and time) for each workload
- [x] Organize the workloads into a set of milestones with increasing complexity
- [x] Identify risks that we might need to tackle along the way
```

Some prior art: https://hackmd.io/w4BM5m50TLONOzeNRSpeOw

**Comment by DamianStraszak** [comment]
Disclaimer: I'm not affiliated with NEAR or Risc-Zero. Just generally interested in these topics.

One approach you guys can also consider is go .wasm -> transpile -> risc-v. And then you can prove execution using a well established tool https://www.risczero.com/. 

See here https://forum.polkadot.network/t/trustless-wasm-compilation-with-snarks/3825 -- a kind of relevant discussion about wasm contracts on substrate chains.

The issue with creating your own ZK-friendly ISA and then implementing a ZK-VM is exactly this -- "implementing a ZK-VM" :). This takes a lot of expert knowledge and lot of man power. Whereas with risc-zero you could potentially just use it out of the box (or almost).

**Comment by akashin** [comment]
Thank you for the suggestion, @DamianStraszak! Risc0 is definitely a promising path that we've considered but ultimately decided to take another route based on [wasmtime/cranelift compiler](https://cranelift.dev/) instead because we think it will lead to better proving times.
The reasoning is the following:
* Cranelift -> WASM is a well-supported path with high-quality optimization passes, WASM -> RiscV is still experimental
* We can tweak [ZK ASM VM](https://wiki.polygon.technology/docs/zkevm/zkASM/basic-syntax/) for our needs to make it a better compilation target, while RiscV ISA is externally defined (which is both good and bad thing)
* [Cranelift provides](https://cfallin.org/blog/2023/01/20/cranelift-isle/) a very flexible model for writing lowering rules from generic Cranelift IR to target ISA which would allow us to incrementally improve the quality of generated code
* Cranelift supports [tools for formal verification](https://www.cs.cornell.edu/~avh/veri-isle-preprint.pdf) of lowering rules which is super important in ZK context

We might re-evaluate this decision in the future but for the next few months, we aim to build an MVP based on Cranelift.

**Comment by akashin** [comment]
We've agreed on the 6-month roadmap: https://hackmd.io/wxRNuku5S8yRk8QDqA6dcA.

The only task left here is the "Risks" section that I will aim to complete this week.

**Comment by akashin** [comment]
I wrote down the Risks section and outlined what we will do to mitigate each of the risks: https://hackmd.io/wxRNuku5S8yRk8QDqA6dcA?view#Risks
This will be a living document, so I'll keep it in Hackmd.

Closing the issue as the planning is complete now.
