### ISSUE TITLE
Questions about operation of ZK ASM

### ISSUE THREAD

**Issue by akashin** [near/nearcore#9564]
A list of questions about ZK asm.
```[tasklist]
### Tasks
- [x] What does CALL instruction does?
- [x] Is there a way to specify a proof for "external function calls" in a separate external location that can be linked together with the input zkASM at a later date?
- [x] How do we want floating point to work? full-on soft float?
```

**Comment by akashin** [comment]
I'm closing this for now, but we can re-open if we have new questions.
