### ISSUE TITLE
🔷 [ProjectTracking] Expand GCS-based State Sync to allow Decentralized transfer of parts

### ISSUE THREAD

**Issue by Sarah-NEAR** [near/nearcore#9575]
# Goals

## Background

State Sync equips validator nodes with State data they need in order to produce blocks. Without it, nodes need to get the state data from outside the chain (e.g. from an S3 snapshot) and constantly spend effort to keep the state up to date with the chain. Decentralised State Sync is the second part of the effort, building a data sharing overlay between the network nodes. It provides a scalable and decentralised way of transferring state parts between nodes.

## Why should NEAR One work on this

State Sync unblocks two features:

- It allows nodes to track a subset of the shards (e.g. chunk-only producers can track a single shard). Since nodes are able to get the state data they need from the network, they no longer required to track all of it locally. Tracking a single shard is one of the main pillars of chain scalability.
- It allows validators and RPC operators to spin-up nodes without relying on the S3 snapshots.

## What needs to be accomplished

Largely, for Decentralised State Sync we need to transfer the generated state parts using an architecture similar to the BitTorrent one.

## Main use case

- Chain scalability, via tracking a sigle shard
- Easier spin-up of nodes, without relying on S3 snapshots.

# Links to external documentations and discussions

Additional resources will be added here when they become available.

# Estimated effort

Engineers assigned: @VanBarbascu, @marcelo-gonzalez and @saketh-are.

Initial effort estimate is about 6-8 PM (person months). Currently remaining effort is presented in the latest comment of this issue.

# Assumptions

There are no specific assumptions that this project is making.

# Pre-requisites

N/A

# Out of scope

N/A

# Task list:

```[tasklist]
### Tasks
- [ ] For 1.38.0
- [ ] https://github.com/near/nearcore/issues/10457
- [ ] https://github.com/near/nearcore/issues/9576
- [ ] https://github.com/near/nearcore/issues/9626
- [ ] https://github.com/near/nearcore/issues/10040
- [ ] https://github.com/near/nearcore/issues/10039
- [ ] https://github.com/near/nearcore/issues/10038
- [ ] -----------------------------------
- [ ] https://github.com/near/nearcore/issues/9633
- [ ] https://github.com/near/nearcore/issues/9627
- [ ] https://github.com/near/nearcore/issues/9625
```

**Comment by gmilescu** [comment]
2023-11-27
- Work still in progress
- Two large items in development: refactoring the actors and implementing peer selection
- Work is split between Node and Core
- Broadcasting shards included in a snapshot is complete.

**Comment by VanBarbascu** [comment]
2023-12-19
* Work in progress
* Items in development:
  * Refactoring code to allow one actor per shard
  * Peer selection
  * Dedicated connection pool for state parts messages
* We have decided to enable DSS after resharding and we aim to have it working in 1.38

**Comment by gmilescu** [comment]
2024-01-26

- Status: Coding work is completed, [last remaining PR](https://github.com/near/nearcore/pull/10441) was approved and merged. We are currently doing integration testing.
- Remaining tasks: integration testing
- Remaining effort: The remaining efort is about 3-4 engineering weeks to be ready for including decentralized state sync into 1.38 finish testing.
- Blockers: None
- Release date: We aim to include Decentralised State Sync in the 1.38 release.
- Note: work on this project was deprioritised until early February to make room for fixing single-shard tracking for Statelessnet and Stake Wars IV.

**Comment by VanBarbascu** [comment]
First release will work for current state of `mainnet` where nodes track all shards.
As mentioned in the previous update, we had no active progress on this project this week.
* **Remaining tasks until first release**: Start new connections to download the parts & header from peers. Refactor the state snapshot storage.

**Comment by VanBarbascu** [comment]
Over the past week we focused on understanding the implication of setting up a new connection. 

Next week we are working the peer connection and state snapshot improvement.

The rest of the plan remains the same:
* set rate limiting for incoming and outgoing requests
* add monitoring
* fine grain controls through configs
* integration testing

Estimated effort is 1 month so we continue planning to releaser it in 1.38.

**Comment by VanBarbascu** [comment]
During the previous week, our focus was on refining the connection between peers for requesting and serving parts. However, this work is still in progress as I was on call for the week.

While we haven't made any advancements in resolving the state snapshot compaction issue, we did identify another problem with the existing implementation. If compaction is enabled on the node, it will crash and fail to clear the generated state parts for the last epoch. Consequently, this leads to a gradual reduction in available storage space on the data partition over time.

The rest of the plan remains the same:
* set rate limiting for incoming and outgoing requests
* add monitoring
* fine grain controls through configs
* integration testing

We are currently on schedule with the project, and we anticipate delivering it by the end of March as planned.

**Comment by bowenwang1996** [comment]
@VanBarbascu will this make into the 1.38 release or not?

**Comment by VanBarbascu** [comment]
Last week, we executed the connection handling on the server side. This week, our agenda includes implementing rate limiting for incoming connections, and establishing connections to request parts from peers. Additionally, we aim to address the issue with state snapshots. Due to a change in the release schedule for version 1.38 with the estimated cut date 5th March, the feature will now be included in 1.39. However, our project timeline remains unchanged, with the goal of shipping the feature by the end of March.

Remaining work includes:
* fine grain controls in configs
* monitoring
* integration testing

**Comment by VanBarbascu** [comment]
2024-03-11

Refactoring of the state sync components is currently in progress. We're in the process of integrating the new peer selection mechanism, which relies on state snapshot host gossip. Regarding the status of the state snapshot fix, it's being actively worked on.

The focus on (DSS) will be reduced for this week until we roll out resharing on the mainnet. As a result, the timeline is expected to be extended by approximately 1.5 weeks, pushing the estimated completion date to the first week of April. Nevertheless, the project remains on schedule to be included in version 1.39.

Remaining work includes:
* fine grain controls in configs
* monitoring
* integration testing

**Comment by VanBarbascu** [comment]
2024-04-01

We fixed the state snapshot size bug and now the snapshot is no longer prohibitively expensive to keep.
Due to the release schedule changes, we reduced the focus on DSS and shifted toward addressing mainnet congestion.

We will resume work on DSS next week with the estimate completion date of end of April.

**Comment by walnut-the-cat** [comment]
> We will resume work on DSS next week with the estimate completion date of end of April.

Is this still accurate?

**Comment by walnut-the-cat** [comment]
Related issue: #12004 
Project doc: [LINK](https://docs.google.com/document/d/1aF0ZDXQVLUyj_zPseIZDhDFQcb2oJWHGz4x2bBrkA8I/edit#heading=h.mliz94l5ykvc)
