### ISSUE TITLE
🔷 [ProjectTracking] Build development and release capabilities using the new Betanet infrastructure

### ISSUE THREAD

**Issue by Sarah-NEAR** [near/nearcore#9578]
# Goals

## Background

Forknet is a infrastructure that can create demand networks with configurable number of nodes, genesis, traffic and node layouts (supporting multiple types of nodes). It replaces the fixed Betanet infrastructure, and will become the default on-demand testing tool.

## Why should NEAR One work on this

For protocol development and troubleshooting it is critical to be able to test various scenarios, both on-demand and consistently on a nightly basis.

## What needs to be accomplished

This project includes: the ability to start networks based on a given node image, the ability to inject traffic, the ability to run the scripts that comprise the tests.

## Main use case

- on-demand testing
- nightly tests (similar to the ones we had in Betanet)

# Links to external documentations and discussions

Additional resources will be added here when they become available.

# Estimated effort

Engineers assigned: @vlad-kopcil with occasional support from other Node team members.

Initial effort estimate is about 4-6 PM (person months). Currently remaining effort is presented in the latest comment of this issue.

# Assumptions

There are no specific assumptions that this project is making.

# Pre-requisites

N/A

# Out of scope

N/A

# Task list:

```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/10042
- [ ] https://github.com/near/nearcore/issues/10043
- [ ] https://github.com/near/nearcore/issues/10041
```

**Comment by gmilescu** [comment]
2023-11-27
- We can start a network with traffic generator. Archival nodes are not supported (legacy ones are the first ones to be supported)
- Polina, Nikolay were able to run the new infra successfully. Marcelo struggled with issues.

**Comment by vlad-kopcil** [comment]
2023-12-18

- added support for achival nodes (legacy mode only)
- shared the setup with devs outside the team, so far so good
- progressing with ability to re-play historical data

**Comment by vlad-kopcil** [comment]
2024-01-16

- we can generate Ansible inventory file from Terraform script
- we have scripts to stop and start neard binary through Ansible
- currently working on saving the inventory file to GCP bucket, so we can have independent pipelines
- also looking into existing tests (pytest, integration, load tests) and trying to get some of these running against forknet cluster

**Comment by gmilescu** [comment]
2024-01-26

- Status: the basic functionality for Forknet is completed. From this point onward we begin integrating it with different scenarios (e.g. pre-release testing, nightly testing, on-demand testing). Therefore we are closing the current issue and will open subsequent ones on a per-need basis.
