### ISSUE TITLE
🔷 October 2023 milestone: Starting threat modeling & adding fuzzers

### ISSUE THREAD

**Issue by Ekleog-NEAR** [near/nearcore#9604]
Previous milestone: #9486 

**Carryover from #9486**
- [ ] Polish up and publish the changes to our security release process
- [x] Finish migrating our cargo-fuzz fuzzers to bolero

**Starting threat modeling**
- [x] Chat with 5 people from protocol about security
- [ ] (Aspirational) Chat with 10 people from protocol about security

**Adding fuzzers**
- [ ] Add fuzzers for host functions
- [ ] (Aspirational) Search for the next best place to fuzz

**Miscellaneous**
- [ ] (Aspirational) Look into our current Hackenproof reports
- [ ] (Aspirational) Investigate which projects could be helpful to us from https://github.com/rust-secure-code/projects

**Comment by Ekleog-NEAR** [comment]
Current status:
- Changes to our security release process are pending review by other people

**Comment by Ekleog-NEAR** [comment]
Status for work up to October 27:

Current status for planned actions:
- Changes to our security review process are pending review by other people
- Migrating our cargo-fuzz fuzzers to bolero is being blocked by our CI woes. I ended up working on improving CI a lot in order to get rid of these regular pain points, instead of working on this
- As a consequences, work on fuzzing host functions has not started yet
- Planned work on threat modeling was completed without issues

Actually done things:
- Got upstream PRs to cargo-bolero to land; moved us back to an officially-released version
- Made us able to build cargo-bolero fuzzers. Actually running them on our infrastructure is what’s currently being blocked by CI woes, and fixing that is my current task

Unplanned things:
- Improved our test suite performance by ~40-60% on CI, and by 10-65% (averaging at 40%) for local development, depending on which test suite is being run
- Looked into our hackenproof report handling process
- In collaboration with the pagoda security team, investigating the snyk tool for security; in consequence landed some dependency upgrade PRs and removed dead code from nearcore
- Almost done getting us out of buildkite, which will unblock all the fuzzer work
- Jumbo-review of in-memory trie nodes code
- Dealt with the branch protection rules debate

**Comment by Ekleog-NEAR** [comment]
Additional work done up to November 1st:
- Reviewed two security-related fixes (nearcore#10007 and nearcore#10023
- Started investigating code coverage tooling
- Completed fixing up the CI infrastructure. Finishing switching the fuzzer infrastructure to the new version is almost over.
- Done some old code cleanup, and upgraded miscellaneous dependencies

Overall for this month, I feel like the CI woes led to much less progress being done on the planned items than expected. Instead, I worked a lot on fixing up CI, which is work that required lots of interactions with in particular non-protocol teams. Additionally, the Snyk audit used quite a bit of time.

All that put together, led to the work on fuzzing host functions being pushed back due to other priorities. Next month will see the Hacken provisional report coming out,
