### ISSUE TITLE
🔷 October 2023 milestone: Onboarding & First steps

### ISSUE THREAD

**Issue by MCJOHN974** [near/nearcore#9617]
Onboarding:
```[tasklist]
### Tasks
- [x] Finish onboarding and take responsibility for zkasm project
- [x] Start actively participate in discussion about zkasm in zulip and calls
- [x] Be able to help with getting in project
```
Make a progress for zkasm stage 1:
```[tasklist]
### Tasks
- [x] Finish all work with docs & infrastructure
- [ ] Support 20 new wasm opcodes for compiler
- [ ] Take a look at ZK processor architecture and changes we want to do in it
```
Explore the protocol (side task)
```[tasklist]
### Tasks
- [x] Make a call with 5 people from other projects and ask them for quick introducing what are they working on
```

**Comment by MCJOHN974** [comment]
@akhi3030, WDYT about this plan?

**Comment by MCJOHN974** [comment]
@akashin, @nagisa, WDYT about this plan, how it correlates with zkasm stage-1 plans?

**Comment by nagisa** [comment]
I think this is alright with regards to zkasm, though I’m not super clear on what some of the points mean. Most notably “make zkasm-computer working with 16 general-purpose registers”. as zkasm hasn’t that many general purpose registers. Are you expecting to contribute such a change to zkasm project? What is the purpose behind it?

More generally, I would say that we should prioritize getting other fundamentals in order. For instance we’re anticipating to use zkasm with 64-bit words and registers (regardless of the register count!) We should absolutely make sure this happens sooner rather than later and make sure that we test against that specific version rather than the 256-bit one. In fact, my view is that register count is perhaps the least of our problems in any case, as we expect to have operations on memory that cost as much as those on registers (meaning there's little point in using registers at all.)

Other than that, I feel like having 20 opcodes implemented is feasible enough in a month, especially if choosing the easier ones to implement ;)

**Comment by MCJOHN974** [comment]
@nagisa, thanks for your comments.
> Are you expecting to contribute such a change to zkasm project? What is the purpose behind it?

We have this point in our stage-1 plan:
```
[Changes to ZK processor](https://github.com/near/wasmtime/blob/main/cranelift/codegen/src/isa/zkasm/docs/roadmap.md#changes-to-zk-processor)
Switch from 256 to 64 bit registers
Have 16 general-purpose registers
Still based on PIL1
```
(https://github.com/near/wasmtime/blob/main/cranelift/codegen/src/isa/zkasm/docs/roadmap.md)

I thought that we should do this changes. Anyway I think I will focus on opcodes implementation, and maybe take a look at ZK processor and changes we want to do, if I will fast enough with the opcodes.

**Comment by nagisa** [comment]
Aha. Yeah, I think it is a good idea to start investigating the 64-bit machine, as the current situation where we're working with a mixture of different versions is not particularly tenable.

> Support 20 new wasm opcodes for compiler

Given the discussion yesterday, I think this is something I think that needs a little bit more planning than just "20 opcodes." I think we should start by picking an interpreter and figuring out what sorts of IR operations it relies on when compiled with clift. We can then pick out the 20 that are easiest to implement or something, but I would take some time on an instruction-by-instruction basis whether implementing them in cranelift for stage1 is the best way forward, or if it would make sense to adjust the interpreter instead (by e.g. pulling in a library on crates.io or something)

**Comment by MCJOHN974** [comment]
Done:

- All onboarding finished
- New opcodes supported: unreachable, mul, div, and, xor, or, ne
- Added tests for existing opcodes: lt_s, lt_u, nop, eqz

**Comment by MCJOHN974** [comment]
Next month plan:

- [ ] Discuss with polygon team how smaller type operations should be performed
- [ ] Take care about proper overflow for smaller types (i32, u32) in simple operations (add, sub, mul, div) and comparing operations (gt, lt, ge, le)
- [ ] Implement bit operations for all types (i32, u32, i64, u64) such that: popcnt, clz, ctz, shr, shl, rotl, rotr, 
- [ ] Discuss with polygon team and implement i64.const, u64.const

**Comment by nagisa** [comment]
@MCJOHN974 you’ll probably need to create a new issue to track next month’s initiatives.

**Comment by MCJOHN974** [comment]
> @MCJOHN974 you’ll probably need to create a new issue to track next month’s initiatives.

Thanks, here it is: [link](https://github.com/near/nearcore/issues/10028)
