### ISSUE TITLE
[DSS] [State Sync] Implement Tier 3 peer pool (includes peer discovery and managing peer conenctions)

### ISSUE THREAD

**Issue by VanBarbascu** [near/nearcore#9626]
Section 6.5 Peer Management of the [DSS doc](https://docs.google.com/document/d/1iisDFsC8m71iqhrM9Ezo-VpXG0LwImUxtljvBoil22s/edit#heading=h.ct570ehsmsit).
```[tasklist]
### Tasks
- [ ] Create TIER3 connection pool for state sync messages
- [x] TIER2 routed messages for state sync peer discovery
- [ ] Initiate connection with peers that can share parts for the shard that the node needs
```
